### ISSUE TITLE
Authentication using phone number only

### ISSUE THREAD

**Issue by itaisteinherz** [aws-amplify/aws-sdk-android#1012]
**State your question**

I need to authenticate and allow users to login to my app using their phone number only, by confirming it (using a one-time password sent using SMS) on registration and on every login.

How could one go about implementing this?
I already tried using the default Amplify CLI wizard, but the login screen it generated always required me to use a username/email address as the primary identification field.

**Which AWS Services are you utilizing?**

- AWS Cognito
- AWS S3
- AWS DynamoDB
- AWS AppSync

**Environment (please complete the following information):**
 - SDK Version: 1.6.5 (found using `$ amplify --version`)

**Device Information (please complete the following information):**
 - Device: Samsung Galaxy S5
 - Android Version: Marshmallow 6.0.1
 - Specific to simulators: No

// cc @ofirsteinherz @undefobj

**Comment by undefobj** [comment]
@itaisteinherz We chatted about this internally and here is the status:
- If you want to just use a phone number AS the username, just select that option and use the phone number for the input field. You might have to build out your UI with `AWSMobileClient` rather than using drop-in auth but it's doable
- If you want an "Alternative SignIn" option, meaning "just select the standard “username only” and use a phone number (to sign in) as well”, then it is not supported by the CLI

For the second one we'd need to do something like this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-aliasattributes

If that's what you're looking for then let's open up an issue in the CLI repo as a feature request.

**Comment by itaisteinherz** [comment]
@undefobj If I understood you correctly, what I'm looking for is the second option. I'll open an issue over at the CLI repo.

**Comment by itaisteinherz** [comment]
Moved to aws-amplify/amplify-cli#1723.
