### ISSUE TITLE
AmazonS3Client upload and download file throw "Wrong version of key store." exception with Android 9

### ISSUE THREAD

**Issue by kltz** [aws-amplify/aws-sdk-android#1090]
Full stacktrace attached.
[trackstrace.txt](https://github.com/aws-amplify/aws-sdk-android/files/3436210/trackstrace.txt)

**To Reproduce(dirty code)**
```
byte[] content = new byte[]{1,2,3,4,5,6};
AWSCredentials awsCredentials = new BasicAWSCredentials("key,"secret");
AmazonS3Client amazonS3Client = new AmazonS3Client(awsCredentials, Region.getRegion("region");
ObjectMetadata objectMetadata = new ObjectMetadata();
objectMetadata.setContentLength(content.length);
PutObjectRequest putRequest = new PutObjectRequest("BUCKET", "MY-OBJECT-KEY", new ByteArrayInputStream(content), objectMetadata);
amazonS3Client.putObject(putRequest);
```

**Environment Information:**
 - AWS Android SDK Version: 2.14.0
 - Device: Simulator, Xiaomi A2 Lite
 - Android Version: Pie 9

**Comment by palpatim** [comment]
@kvasukib Related to keystore issues?

**Comment by kvasukib** [comment]
@kltz Sorry for the delayed response. This issue is not related to AWS SDK for Android and I suspect it is related to `okhttp`.

The AWS SDK for Android has a HTTP client implementation that is a wrapper on top of the default HTTP client implementation given by the Android Platform and the Android device. In this case, from the stacktrace I can see that `okhttp` client library is being used for making the HTTP requests.

There are multiple issues I could see from the stack-trace:

1) The version of `okhttp` client used in your app/Android platform/Android device is relying on the Bouncy Castle library which is deprecated in Android 9 and it erred out with wrong version of keystore. This could be due to a version of `okhttp` that is being used by your app that is relying on Bouncy Castle whereas it shouldn't because Android deprecated and is in the process of removing it.

2) The `okhttp` client couldn't locate the `AndroidOpenSSL` cryptographic algorithm provider which is required for operations with `SSLSocket`.

I would recommend you to check with the version of `okhttp` client library being used by your app/Android Platform 9/Android device you are running and check with the `okhttp` repository for issues related to this.
