### ISSUE TITLE
KMS module not working

### ISSUE THREAD

**Issue by adityaprajapati5687** [aws-amplify/aws-sdk-android#1096]
I want to integrate with KMS module in android, means I want to create a key, encrypt data and decrypt data from android app.

it is not working.

**Comment by palpatim** [comment]
@adityaprajapati5687 

Could you please provide more detail to help us understand your problem? The "Bug" template "New issue" is the minimum information we need:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**
Add any other context about the problem here.
