### ISSUE TITLE
Unable to set 'CognitoUserAttributes.mfaOptions' in request of /signUpInBackground API call

### ISSUE THREAD

**Issue by bveenvliet** [aws-amplify/aws-sdk-android#1106]
**Which AWS Services is the feature request for?**
Cognito user registration / signUp

**Is your feature request related to a problem? Please describe.**
Cognito user registration / signUpInBackground() has a parameter CognitoUserAttributes but you are unable to set the private field mfaOptions. The business requirement I am trying to meet is that SMS MFA be decided by new users during registration.

**Describe the solution you'd like**
I'd like to see a way to set the mfaOptions and have it work when this is sent to the API.

**Describe alternatives you've considered**
I tried creating my own CognitoUserAttributes class and set the mfaOptions with a key value pair of "phone_number":"SMS" and sent this to the signUp API but SMS MFA was not enabled when checking on the AWS Cognito web portal and attempting to sign in afterwards.

**Additional context**
None

**Comment by desokroshan** [comment]
@bveenvliet Thanks for reaching out. Quick clarification, are you using [AWSMobileClient.signUp](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1679) or are you using [CognitoIdentityProvider](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool.java#L368). We recommend using AWSMobileClient for everything auth. Please let us know if you have issues using it.
Regarding your particular problem, can you try to pass the mfaOptions(the key-value pairs) along with the other user attributes in the userAttributes map accepted by the MobileClient signup method](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1679) or in the [userAttributes field](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes.java#L34) of the CognitoUserAttributes parameter accepted by [CognitoUserPool's signUpInBackground method](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool.java#L368). I suspect the mfaOptions field in CognitoUserAttributes class might be redundant since the SignUpRequest(https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/model/SignUpRequest.java) does not have a specific field for mfaOptions. SignUpRequest is finally passed to the service with all the required information.

**Comment by bveenvliet** [comment]
I'm using CognitoUserPool.signUpInBackground() directly which is a part of the aws-android-sdk-cognitoidentityprovider.
    implementation "com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.14.0"

I cannot use AWSMobileClient.signUp() as it doesn't allow you to pass in the mfaOptions.
In the original feature request under "Describe alternatives you've considered", I mentioned that I tried passing in mfaOptions of "phone_number":"SMS" and it was not working/enabled when I tried this.

**Comment by desokroshan** [comment]
@bveenvliet Thanks for the clarification, I was a little confused by your initial message when you said "I tried creating my own CognitoUserAttributes class". I think you meant you instantiated the `CognitoUserAttributes` and added the key-value pair `"phone_number":"SMS"` to it? Is that the correct? Can you please share the relevant code snippet?

**Comment by bveenvliet** [comment]
https://gist.github.com/bveenvliet/e421c0173c634f465f1c33d1740115c9

**Comment by desokroshan** [comment]
mfaOption that you passed in the class above will not be passed down to service since the [SignUpRequest](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/model/SignUpRequest.java) class does not have a property corresponding to mfaOption. As pointed out above, you should try to add `"phone_number":"SMS"` to the [userAttributes field](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserAttributes.java#L34) of the CognitoUserAttributes parameter accepted by [CognitoUserPool's signUpInBackground method](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserPool.java#L368). You should not have to create a new CognitoUserAttribute class. Let me know if that works.
