### ISSUE TITLE
Migrate users with a Lambda Trigger

### ISSUE THREAD

**Issue by Nikooos** [aws-amplify/aws-sdk-android#1136]
I'm trying to migrate users from our existing user management system into our user pool without a password reset. 

For iOS I found [this example](https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-ios-sdk-user-migration-lambda.html) which explains that adding a boolean to the awsconfiguration.json with the key MigrationEnabled and value YES should do the magic. This works.

For Android I found [an example](https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-android-sdk-user-migration-lambda.html) which totally doesn't match our Kotlin setup. For Android we're also using the awsconfiguration.json, but the MigrationEnabled boolean is not doing any magic in this case. Unfortunately with this documentation I can't figure out how to do this in our Android app.

Can anyone point me in the right direction for this?

**Environment:**
 - SDK Version: 2.14.2

**Comment by patrickkempff** [comment]
Having the same issue, not sure how to set `MigrationEnabled` on Android

**Comment by patrickkempff** [comment]
@palpatim thank you for your reply.

I am indeed using AWSMobileClient, mostly because the docs recommend it. Is there an other way to do it without the need of implementing scenario's like transitioning from offline to online and refreshing credentials at the appropriate time so that errors do not occur when actions are taken and connectivity is not available?

**Comment by htrujill** [comment]
Will custom migrations using LambdaTriggers be supported soon in AWSModileClient?

**Comment by patrickkempff** [comment]
Any updates on this?

**Comment by kneekey23** [comment]
Adding our PM @nikhil-dabhade to add insight here on timeline for this feature request.

**Comment by fernandoaguilar** [comment]
any updates on this? We have the same issue and need this to work.

**Comment by VinnyScorsatto** [comment]
Any Updates on this?

**Comment by patrickkempff** [comment]
Any updates? 😢

**Comment by MichaelHighsmith** [comment]
Has anyone found a solution to this for Android? MigrationEnabled is working for iOS but that's it.

**Comment by MichaelHighsmith** [comment]
For anyone down the road I found the solution for Android. Rather than setting the migrationEnabled field, you need to create AuthenticationDetails and AuthenticationHandler objects, set the detail's authenticationType to "USER_PASSWORD", and then call initiateUserAuthentication on your cognitoUserPool instance. Below is an example:

val authenticationHandler: AuthenticationHandler = object : AuthenticationHandler {

    override fun onSuccess(cognitoUserSession: CognitoUserSession?, device: CogntioDevice?) {
        //get your login token here
    }

    //other overridden methods here

}

val authDetails = AuthenticationDetails(email, password, null)
authDetails.authenticationType = "USER_PASSWORD"
cognitoUserPool?.currentUser?.initiateUserAuthentication(authDetails, authenticationHandler, true)?.run()

**Comment by fernandoaguilar** [comment]
to add to @MichaelHighsmith solution, we ended up doing the same thing and in the onSuccess call we just called login with amplify again and that handled the tokens for us.

**Comment by MichaelHighsmith** [comment]
@fernandoaguilar It seems that on a fresh install when I try to call cognitoUserPool?.currentUser, that user has a null userID which is throwing a wrench in the authentication. I think signing in a dummy user and then using that user's ID to do the real login would work, but it's definitely not the right way to go. Do you have any advice on how you got around this issue?

**Comment by fernandoaguilar** [comment]
@MichaelHighsmith  create a cognito user with the users email when they login.
```java
    CognitoUser cognitoUser = cognitoUserPool.getUser(email);
```

**Comment by MichaelHighsmith** [comment]
Wow I guess I'd been staring at this for too long...thanks for the help @fernandoaguilar !

**Comment by fernandoaguilar** [comment]
@MichaelHighsmith no problem!

**Comment by TrekSoft** [comment]
Thanks for posting that solution @MichaelHighsmith and sorry everyone for the extended blackout on this ticket! Came up on my radar here with the large number of recent comments. I'll close the issue for now but if others are having difficulties with this, leave a comment and I can reopen it.
