### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: SSL handshake aborted:

### ISSUE THREAD

**Issue by tanujsai** [aws-amplify/aws-sdk-android#1177]
**Describe the bug**
In Android 4.x we are observing SSL handshake aborted for subscription initialization. 

 **To Reproduce**
Can be reproduced by using any kitkat (4.4.X) devices 

 **Which AWS service(s) are affected?**
AWS Subscription feature.
  
 **Error Logs**
 ```
09-04 10:05:19.273 2207-2531/com.app W/RetryInterceptor: Encountered IO Exception making HTTP call [javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb9776120: Failure in SSL library, usually a protocol error
    error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x9896d990:0x00000000)]
09-04 10:05:19.273 2207-2531/com.app D/SyncActivity: com.apollographql.apollo.exception.ApolloNetworkException: Failed to execute http call
 ```

**Environment Information**
 - AWS Android SDK Version: 2.13.7
-- com.amazonaws:aws-android-sdk-core:2.13.7
-- com.amazonaws:aws-android-sdk-appsync:2.10.0
-- org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0
-- org.eclipse.paho:org.eclipse.paho.android.service:1.1.1

 - Device:  Android Studio Emulator
 - Android Version: 4.4.2
 - Specific to simulators: [e.g. Yes/No] Specific to android version 

Can someone please add there input that helps to resolve it.
Thanks in advance

**Comment by mzeccavb** [comment]
Experienced same issue with AppSync using JellyBean device

**Comment by kvasukib** [comment]
@tanujsai Sorry for the inconvenience caused. 

In my research in Android documentation, I have observed the following:

- On devices older than Android 5.0 TLSv1.1 and TLSv1.2 protocols are not enabled by default.
- SSLv3 protocol is not disabled by default on devices older than Android 5.0.
- SSLv3 is not a secure protocol and it is therefore desirable to remove it from our client's list of supported protocols before a connection is made.

**The following statement is a theory**

It is possible that in Android 4.4 the TLSv1.1 and TLSv1.2 protocols are not enabled by default and they are not found by `OkHttpClient` when it is tried to create an instance of the `Socket` through the default `SocketFactory`.

Have you observed the same behavior in devices lower than KitKat (4.4)? If my theory holds good, you should be seeing these failures in even lower devices.

Do you have any code in your app that registers or de-registers Security Providers at runtime or do you specify any overriding configuration in your app which will add/remove Security Providers or change the order in which Android searches for one?

One possible workaround I could think if my theory holds good would be to write a custom `SocketFactory` that works for these devices and add it to the `OkHttpClient` object. Then, you can pass the `OkHttpClient` object to the `AWSAppSyncClient.Builder` instead of the SDK constructing it.
