### ISSUE TITLE
User is not allowed to login on entering email id in upper case

### ISSUE THREAD

**Issue by SubirZ** [aws-amplify/aws-sdk-android#1332]
Hi all,

we are facing an issue when attempting sign in using the username in uppercase (In our case the username is an email address).

Steps to reproduce:
Actual username and password:
some.user@gmail.com
Asdf123@

Username entered in uppercase
SOME.USER@GMAIL.COM

I've tried on a Pixel 2XL with Android 9.(emulator)
Pixel2 with Android 9.(device)

Thanks in advance for the help!

**Comment by desokroshan** [comment]
@SubirZ Thanks for the reaching out. Can you please share details of the SDK you are using?
1. Are you using AWSMobileClient or the CognitoIdentityProvider SDK
2. What version of SDK are you using?

**Comment by SubirZ** [comment]
@desokroshan  Thanks for the reply. Eagerly waiting for the resolution.
Thanks

**Comment by lawmicha** [comment]
hi @SubirZ , could you confirm, if i sign up with an email like "some.user@gmail.com", then try to sign up again with another email like "SoMe.UsEr@gmail.com", is this successful or will it be recognized as an existing user?

**Comment by lawmicha** [comment]
hi @SubirZ , I was able to reach out to the service team regarding this issue;
- existing cognito set ups will remain the same, so users that sign up for an account with a particular case sensistivity will have to put in the same casing when logging in. there is no migration plan.
- the feature for case insensitivty so that users can sign in using the same email with different casing is currently being worked on. when this is launched, you would have to set up a new cognito user pool to use this feature.

From the developer's perspective, i would suggest converting the username to lower case before sign-in/log-in to maintain a consistent sign-up/login experience.

**Comment by SubirZ** [comment]
hi @lawmicha, I am glad to receive such a reply. Your effort is really appreciable. That's a good idea "converting the username to lower case before sign-up/log-in to maintain a consistent sign-up/login experience".

I case of signing up using ```some.user@gmail.com``` and ```SoMe.UsEr@gmail.com``` two different users are being created.

**Comment by div5yesh** [comment]
Usernames and email addresses are now case insensitive by default for new Cognito user pools.
