### ISSUE TITLE
Failed to get credentials from Cognito Identity when testing aws-sdk-android-samples/AndroidPubSub/

### ISSUE THREAD

**Issue by Jade0101** [aws-amplify/aws-sdk-android#1346]
I am testing aws-sdk-android-samples/AndroidPubSub/ from https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub.

Enviroment setting is,
`dependencies {
    def aws_version = "2.16.+"
    implementation "com.amazonaws:aws-android-sdk-iot:$aws_version"
    implementation "com.amazonaws:aws-android-sdk-mobile-client:$aws_version"
    implementation "com.android.support:support-compat:26.0.0"
}`
`compileSdkVersion 26`
`defaultConfig {
    versionCode 1
    versionName "1.0.0"
    minSdkVersion 19
    targetSdkVersion 26
}`

And I configured like
`private static final String CUSTOMER_SPECIFIC_ENDPOINT = "a2k94wsqkar4rm-ats.iot.us-west-2.amazonaws.com";`
`private static final String AWS_IOT_POLICY_NAME = "Android_Client_Policy";`
`private static final Regions MY_REGION = Regions.US_WEST_2;`
`"PoolId": "us-west-2:6a4f3b9a-cebc-4e6f-b5eb-00493c25b8b7",`
`"Region": "us-west-2"`

But I always get these error,

> com.amazonaws.AmazonClientException: Failed to get credentials from Cognito Identity

> Unable to execute HTTP request: Failed to connect to cognito-identity.us-west-2.amazonaws.com/2600:1f14:179:3f00:a293:762:e314:909a:443

Along with some other errors,

> com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.mobile.client.aesKeyStoreAlias

> Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = provider

**Comment by HeinousGames** [comment]
Our production app is also having issues getting the cognito caching credential provider. We updated the library to 2.16.4 but the issue still remains. Not sure what is going on here.

**Comment by AgiMaulana** [comment]
Try getDetailsInBackground(), you guess you call getDetails(), which is run HTTP request on mainThread.

**Comment by HeinousGames** [comment]
Our problem ended up being that some proguard removed classes that facilitated the connection for the cognito caching credential provider. The default proguard rules that Amazon provides were enough, but after adding a couple of Google dependencies they ended up conflicting and the proguard rules failed. We had to add extra proguard rules that were originally used by the Amazon team and were possibly deprecated (as they were on older repos/tutorials)

**Comment by WassimErriha** [comment]
@ HeinousGames  what Proguard rules did you endup adding ?
I am having the same issue you described.

**Comment by WassimErriha** [comment]
@HeinousGames  what Proguard rules did you endup adding ?
I am having the same issue you described.

**Comment by HeinousGames** [comment]
@WassimErriha I've included the rules that I added to our proguard project. I'm not including all of our rules, just what I ended up adding. If it doesn't work for you, let me know and I will try to help.

Amazon Rules:
-keepnames class com.amazonaws.** { *; }
-dontwarn org.apache.commons.logging.impl.**
-dontwarn org.apache.http.conn.scheme.**
-keep class org.apache.commons.logging.**               { *; }
-keep class com.amazonaws.services.sqs.QueueUrlHandler  { *; }
-keep class com.amazonaws.javax.xml.transform.sax.*     { public *; }
-keep class com.amazonaws.javax.xml.stream.**           { *; }
-keep class com.amazonaws.services.**.model.*Exception* { *; }
-keep class org.codehaus.**                             { *; }

-dontwarn javax.xml.stream.events.**
-dontwarn org.codehaus.jackson.**

-keep class com.amazonaws.internal.**                    { *; }
-keepattributes Signature,*Annotation*,EnclosingMethod
-keepnames class com.fasterxml.jackson.** { *; }

#SDK split into multiple jars so certain classes may be referenced but not used
-dontwarn com.amazonaws.services.s3.**
-dontwarn com.amazonaws.services.sqs.**

-dontnote com.amazonaws.services.sqs.QueueUrlHandler

**The reason we had to update these rules was because Google's web client libraries conflicted with Amazon's. Here are some rules we also added for Google's libraries:**
#Needed to keep generic types and @Key annotations accessed via reflection
-keepattributes Signature,RuntimeVisibleAnnotations,AnnotationDefault,*Annotation*
#Needed by google-http-client-android when linking against an older platform version
-dontwarn com.google.api.client.extensions.android.**

#Needed by google-api-client-android when linking against an older platform version
-dontwarn com.google.api.client.googleapis.extensions.android.**

#Needed by google-play-services when linking against an older platform version
-dontwarn com.google.android.gms.**

#com.google.client.util.IOUtils references java.nio.file.Files when on Java 7+
-dontnote java.nio.file.Files, java.nio.file.Path

#Suppress notes on LicensingServices
-dontnote **.ILicensingService

#Suppress warnings on sun.misc.Unsafe
-dontnote sun.misc.Unsafe

#Needed by Guava
#See https://groups.google.com/forum/#!topic/guava-discuss/YCZzeCiIVoI
-dontwarn com.google.common.collect.MinMaxPriorityQueue

-keep class * extends com.google.api.client.json.GenericJson {
*;
}
-keep class com.google.api.services.drive.** {
*;
}

-keep class com.google.** { *;}
-keep interface com.google.** { *;}
-dontwarn com.google.**

**Comment by eeatonaws** [comment]
We have removed the AndroidPubSub sample as the code is outdated. Please see the [PubSub documentation](https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android/) for more information on setting up and working with PubSub.
