### ISSUE TITLE
TransferUtility - possible to use multiple S3 clients (or creds/settings)?

### ISSUE THREAD

**Issue by tomfielder** [aws-amplify/aws-sdk-android#1382]
I have a use case for the TransferUtility where I need to be able to upload files to different buckets/keys/regions using potentially different credentials. So, it'd be great if I was able to specify the S3 client to use at the time of initiating the upload.

I can see in `TransferUtility.submitTransferJob(...)` that it stores references to the S3 client via `S3ClientReference.put(id, s3)`. So, unless I'm missing something, it looks like the utility is already keeping track of which transfer uses which S3 client?

Is it possible to expose the changing of the S3 client used on a per transfer basis?

**Comment by desokroshan** [comment]
@tomfielder Thanks for reaching out. TransferUtility currently does not support the ability to use multiple S3 clients. I have marked this as a feature request and will update the thread with more details after discussion with the team.

**Comment by lon9man** [comment]
### another use case

application have 2 different upload's type:
1. upload all photos from device into bucket XXX (like synchronization)
2. upload concrete photo(-s) into different buckets YYY

AFAIU TransferUtility has 1 internal table with hardcoded name `awstransfer`, where it saves data about files to upload.
BUT we need to differentiate in some way records in table to understand what of upload's type it is related.

It seems we needs to have multiple separate TransferUtility's instances with completely different options, database table name and etc.

for example:
- **each upload's type** should have separate UI in application
- we should show progress **per each upload's type**, so we need to select data from different tables (TransferObserver, ...)
- we should have possibility to make pause/resume **per each upload's type**

currently it is hard to implement our application flow without some over-architected things. 
does exist some simpler way to resolve our use case?

**Comment by lon9man** [comment]
any reaction about [my previous post](https://github.com/aws-amplify/aws-sdk-android/issues/1382#issuecomment-923816862)?

**Comment by sdhuka** [comment]
@lon9man It is not possible to have a different awstransfer database for each instance of transferUtility. Except for the last one, where you want to pause/resume using the upload type, you can achieve most of your usecases with two instances of TransferUtility. Instead, you can query all the transfers using `getTransfersWithTypeAndState` and then pause/resume individual transfers using a transferObserver instance.

**Comment by lon9man** [comment]
@sdhuka 
>  It is not possible to have a different awstransfer database for each instance of transferUtility

as for end developer it will be pretty useful, because we can completely separate concerns for different upload types. each transferUtility-instance knows only about saying 1 upload type, it saves data into separate database, it uploads this upload type in parallel manner, when other transferUtility-instance also uploads in the same time another upload type without waiting each other and user can see progress of both in UI. maybe feature-request? :)

## Question
so it is also impossible to implement parallel uploading of files with different upload types?
for example:
[1.] synchronization (upload into bucket FOO)
[2.] upload into concrete album (upload into bucket BAR)

did i correctly understood that user will not see any progress in upload [2.] BEFORE all files of [1.] will be finished?

**Comment by sdhuka** [comment]
Each instance of transferUtillity will have seperate threadpool so upload using separate instance will run in parallel.
