### ISSUE TITLE
Issue regarding Invalid login token

### ISSUE THREAD

**Issue by depak330** [aws-amplify/aws-sdk-android#1431]
**Describe the bug**
Some time show this error Invalid login token. Not a Cognito token. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: *********) .but if try again then it give success status.

**Comment by jamesonwilliams** [comment]
Hi @depak330, thanks for contacting us. We need more information in order to assist you. Kindly look at [the template for a usage question](https://github.com/aws-amplify/aws-sdk-android/issues/new?template=usage_question.md), and provide all requested information. Feel free to re-open when you've done this.

**Comment by depak330** [comment]
Hello @jamesonwilliams Thanks for reply now issue resolved.
