### ISSUE TITLE
Error encountered during multi-part upload (403 error)

### ISSUE THREAD

**Issue by BlackDevs** [aws-amplify/aws-sdk-android#1463]
**State your question**

Hi Guys! I try to upload image to bucket and get 403 error.
Please help me, what i do wrong?)

 val key = "protected/avatars/${userId}/${avatar.name}"
        val poolId = "eu-west-1:some_id"
        val bucket = "some_bucket"

        val metadata = ObjectMetadata()
        metadata.contentType = "image/jpeg"

        val credentialsProvider =
            CognitoCachingCredentialsProvider(context.applicationContext, poolId, Regions.EU_WEST_1)
        
        val mapLogins = HashMap<String, String>()
        mapLogins["cognito-idp.eu-west-1.amazonaws.com/eu-west-**************"] = prefs.getIdToken() <--- this is my token from server side
        credentialsProvider.withLogins(mapLogins)

        val client = AmazonS3Client(credentialsProvider)

        val transferUtil: TransferUtility =
            TransferUtility.builder().context(context)
                .awsConfiguration(AWSMobileClient.getInstance().configuration)
                .s3Client(client)
                .build()

        val transferObserver: TransferObserver =
            transferUtil.upload(
                bucket,
                key,
                File(avatar.absolutePath),
                metadata,
                CannedAccessControlList.PublicRead
            )
 - SDK Version: 2.10.1

**Comment by raphkim** [comment]
Hi @BlackDevs ,

Thank you for reaching out to us. Would you be able to provide us with more detail so that we may assist you better? A stack trace where your code breaks would be helpful in identifying what the cause of issue is. 

Meanwhile, I notice that you are setting your key to store item in `"protected/avatars/${userId}/${avatar.name}"`. However, the policies generated by CLI for restricting access apply to resources that are prefixed with `"{access-level}/{userId}/"`. 

Would you be able to try again with `"protected/${userId}/avatars/${avatar.name}"` (and make sure that the resources are organized accordingly in the S3 bucket) and see if you are able to correctly apply the restricted access policies on the resources?
