### ISSUE TITLE
getIdentityId() returns null the first time after Sign In in Android, crashes app but if reopened behaves normally

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/aws-sdk-android#1510]
**Describe the bug**

`getIdentityId()` returns `null` the first time after signing in. This will
crashes the app. But when the app is reopened, things behave normally. 

Here's the code that I have tried:
```java
CognitoCachingCredentialsProvider credentialsProvider =
    new CognitoCachingCredentialsProvider(
        getApplicationContext(), // Context
        "IDENTITY_POOL_ID", // replaced by Identity Pool ID of mine 
        Regions.AP_SOUTH_1// Region
    );
new Thread(new Runnable() {
    @Override
    public void run() {
       String identityId = credentialsProvider.getIdentityId();
    }
}).start();
```

Had to start a new thread as it was giving error about using the main thread.
Another thing I tried:
```java
new Thread(new Runnable() {
     @Override
     public void run() {
         final AWSCredentials credentials = AWSMobileClient.getInstance().getCredentials();
     }
}).start();
String identityId = AWSMobileClient.getInstance().getIdentityId();
```

Here's the error that shows up in Logcat:
> Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied;

I get this same result every time.

**Expected behavior**
Normal, smooth login

**Desktop (please complete the following information):**
 - OS: [Android Oreo]

Thank you for your valuable time.

------------------------

Update:

Actually, the issue is that the identity ID I am getting from these methods
calls the `getIdentityId()` 2 or 3 times within few seconds. If it is called 3
times, then one time it mostly comes `null`. One is right, and one is wrong.
This crashes the app, but when restarted it behaves normal. I somehow took the
ID in a `final` String and it's currently works but please solve the bug.

Thank you.

**Comment by Diegolotr99** [comment]
is anyone even looking at this issues ???

**Comment by jamesonwilliams** [comment]
@Diegolotr99 ___Yes !!!___ 😆  Please share details of your error.

**Comment by Diegolotr99** [comment]
Hey @jamesonwilliams ,
It might not be exactly the same error as the one in this ticket, but I am desperate at this point.
So hopefully you can help me or guide me in the right direction.
The flow I am following is the next: 

- Request Sign In with an email and a null password to get the SMS code through the Cognito Lambdas.
   ` Amplify.Auth.signIn(username, null)`
- First time I sign in everything works perfectly. I get the SMS and enter the code and sign in out successfully.
   In order for this to work I do the code confirmation through AWS Mobile Client directly, because Amplify method to confirm code does not work `Amplify.Auth.confirmSignIn(code) ->` (AuthException{message=Confirm sign in failed, cause=java.lang.IllegalStateException: confirmSignIn called on unsupported operation, please file a feature request, recoverySuggestion=See attached exception for more details.})
  But if I use AwsMobileClient.confirmSignIn(code) it works fine. 

- Then I perform a SignOut , if I try a Sign In right after, I get the SMS code but the confirm sign in replies with CustomChallenge and not successful, I navigate back and try a sign in again, get a new sms code and this time the sign in confirmation works perfectly. 

But I can't release this app with a bug telling the users that if they sign out, then the first time they'll try to sign in again it will not work, to just try again.

**Comment by raphkim** [comment]
Hi @Diegolotr99 ,

It appears that you are experiencing an issue with our Amplify framework. Would you be able to open a new ticket in our the [Amplify Framework for Android repository](https://github.com/aws-amplify/amplify-android/issues) regarding your issue?

**Comment by Diegolotr99** [comment]
Thank you @raphkim , here it is, I opened the following issue: https://github.com/aws-amplify/amplify-android/issues/962

**Comment by Diegolotr99** [comment]
Why aws-amplify DELETING COMMENTS ??

**Comment by jamesonwilliams** [comment]
Hi, @Diegolotr99. It's much less exciting of an explanation than you've imagined. I condensed some information back into the original post, that's all. Cheers.

**Comment by Diegolotr99** [comment]
Hi @jamesonwilliams , Cheers. Still looking for any help here -> https://github.com/aws-amplify/amplify-android/issues/962

**Comment by jamesonwilliams** [comment]
@Diegolotr99 Please do not spam unrelated issues, to advertise your other issues. That creates noise for folks who are trying to follow this ticket. If you have additional engineering details to provide on this ticket, please do so.

**Comment by gpanshu** [comment]
HI @abhidaa1233 please advise if this is still an issue as this github issue is quite old. Please try with the latest libraries. If this is still happening we will do a deep dive and fix it.
