### ISSUE TITLE
Runtime exception with Cognito

### ISSUE THREAD

**Issue by BoykoDmytro** [aws-amplify/aws-sdk-android#1512]
**Describe the bug**
Is it possible then the user is deleted throw IllegalStateException or IllegalArgumentException that application can logout user automatically?

```
2020-03-12 14:58:37.038 3003-3103/com.unyte.ils E/AndroidRuntime: FATAL EXCEPTION: Thread-14
    Process: , PID: 3003
 com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoParameterInvalidException: user ID cannot be null
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.util.CognitoSecretHash.getSecretHash(CognitoSecretHash.java:45)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.initiateUserSrpAuthRequest(CognitoUser.java:2872)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.access$2200(CognitoUser.java:132)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$24.run(CognitoUser.java:2461)
        at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$7$1.run(CognitoUser.java:882)
        at java.lang.Thread.run(Thread.java:764)
```

**To Reproduce**
A code sample or steps:
```
suspend fun refreshToken() = suspendCancellableCoroutine<PendingResult> {
        val cognitoUser = cognitoUserPool.currentUser
        cognitoUser.getSessionInBackground(AuthenticationHandlerImpl(it, REFRESH_TOKEN_PASSWORD))
    }
```

**Which AWS service(s) are affected?**
`com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.16.8`

**Expected behavior**
I think the best way to throw IllegalArgumentException with the same error user ID cannot be null.

**Environment Information (please complete the following information):**
 - `com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.16.8`
 - Device: no matter (One plus A6000)
 - Android Version: no matter (Android 10)
 - Specific to simulators: No

**Comment by raphkim** [comment]
Hi @BoykoDmytro ,

Thank you for reaching out to us regarding a potential bug. To help us identify the issue, would you be able to clarify what you mean by "deleting" a user? 

Also I must add that throwing a runtime exception over `CognitoParameterInvalidException` would not be something that we, as an SDK team, can do, since it is a well-defined error on the Cognito service side.

**Comment by BoykoDmytro** [comment]
Hi, sorry for the late response, delete user from congito at all. There is no error message on callback.

**Comment by BoykoDmytro** [comment]
@raphkim any news?

**Comment by raphkim** [comment]
Hi. You wish for the SDK to throw a "user ID cannot be null" error when you delete a Cognito user, is that correct?

May I ask whether you are deleting a Cognito user via console or code? If you are doing this by directly using the `aws-android-sdk-cognitoidentityprovider` SDK, then your option is to simply sign out upon successful deletion. However, if you are deleting a user from the console, then the SDK will not throw any error until another service API call is made using deleted credentials.

**Comment by BoykoDmytro** [comment]
Steps to reproduce
1) User has been registered on Congito pool 1 and logged in
2) User has been totally removed from Cognito pool
3) User try to refresh token 
The SDK throws CognitoParameterInvalidException.

Steps to reproduce
1) User has been registered on Congito pool 1 and logged in
2) Switch config to other pool without this user
3) User try to refresh token 
The SDK throws CognitoParameterInvalidException.

**Comment by raphkim** [comment]
Okay I believe I understand what is happening. Attempting to sign in by obtaining user session after the user is deleted will not throw any error because the SDK caches the user session information. Only after the cache expires will you receive `UserNotFoundException` from Cognito. This behavior is by design, and we are likely not going to introduce any code changes for detecting user deletion before token expiration (as that would defeat the purpose of having a cached user session to begin with).
