### ISSUE TITLE
Error encountered during multi-part upload: 1 due to Invalid identity pool configuration. Check assigned IAM roles for this pool

### ISSUE THREAD

**Issue by abbasalid** [aws-amplify/aws-sdk-android#1525]
I have tried all possible combinations on cognito,s3 with IAM Roles but I am not able to solve this issue

**Comment by raphkim** [comment]
Hi @abbasalid ,

Thank you for reporting an issue. I understand that you are frustrated that you are unable to complete multipart upload via S3. May I ask for a code snippet and a log so that I may better assist you? Meanwhile would you be able to verify the following?
- Are you using `TransferUtility` to upload a file?
- Is your `res/raw/awsconfiguration.json` configured with valid identity pool ID and region? S3 bucket and region?
- If you have identity pool correctly set up, is it correctly linked to the correct user pool?

Thank you.

**Comment by abbasalid** [comment]
In app level build gradle

`implementation 'com.amazonaws:aws-android-sdk-s3:2.7.+'
implementation 'com.amazonaws:aws-android-sdk-cognito:2.7.+'
 implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.7.+@aar') { transitive = true }`

My piece of java code
 `TransferUtility transferUtility = TransferUtility.builder()
                            .context(getApplicationContext())
                            .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                            .s3Client(new AmazonS3Client(AWSMobileClient.getInstance().getCredentialsProvider()))
                            .build();

            TransferObserver uploadObserver = transferUtility.upload(
                            BucketName,  //bucketname
                            displayName,//filename
                            f,//file
                            CannedAccessControlList.PublicRead );

            // Attach a listener to the observer to get state update and progress notifications
            uploadObserver.setTransferListener(new TransferListener() {
                @Override
                public void onStateChanged(int id, TransferState state) {
                    if (TransferState.COMPLETED == state) {
                        // Handle a completed upload.
                    }
                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                    float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                    int percentDone = (int)percentDonef;

                    Log.d("YourActivity", "ID:" + id + " bytesCurrent: " + bytesCurrent
                            + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
                }

                @Override
                public void onError(int id, Exception ex) {
                    // Handle errors
                }

            });
            if (TransferState.COMPLETED == uploadObserver.getState()) {
                // Handle a completed upload.
            }
        }`

Here is my awsconfiguration.json file
`{
    "Version": "1.0",
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:xxxxxxxxxxxxxxxx",
                "Region": "us-east-1"
            }
        }
    },
    "IdentityManager" : {
      "Default" : { }
    },
    "S3TransferUtility": {
        "Default": {
            "Bucket": "bucketname",
            "Region": "ap-south-1"
        }
    }
}`
I am having serious doubt regarding identity Id like there are different identity pool id in cognito in different locations. I don't know which one to use

**Comment by raphkim** [comment]
Hi @abbasalid 

Thank you for providing us with the requested information. I have a few suggestions to start off:
- Firstly, I see that you are using an outdated version of our SDK. Please try using our [latest release](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.8) if possible for the best experience.
- Additionally, it is recommended to reuse the same `TransferUtility` instance rather than re-instantiating per upload attempt so that it can smoothly manage multiple transfers without any issue.

As for the main issue that you are experiencing, would you be able to try the following?
1. Go to AWS Cognito console -> Manage Identity Pools
2. Select the identity pool linked to your app 
3. Click "Edit identity pool"
4. Check `Enable access to unauthenticated identities` under  "Unauthenticated identities" to `true`
If you follow the above steps (for debugging purposes only) and do not experience the error, then we would be able to scope the issue down to Cognito user pools configuration. If you are still experiencing error after, then please feel free to let us know by commenting in this thread.

**Comment by abbasalid** [comment]
Hello @raphkim  I had already given access to unauthenticated identities.
I have been using code given in the [link](https://github.com/awsdocs/aws-mobile-developer-guide/blob/master/doc_source/how-to-integrate-an-existing-bucket.rst)
Or should I use this below code:
`private class S3Example extends AsyncTask<Void,Void,Void>{
        @Override
        protected Void doInBackground(Void... params) {
        
            // Initialize the Amazon Cognito credentials provider
            CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                MY-ACTIVITY.getApplicationContext(), // Application Context
                "MY-IDENTITY-POOL-ID", // Identity Pool ID
                Regions.SELECT_YOUR_REGION // Region enum
            );

            AmazonS3Client s3Client = new AmazonS3Client(credentialsProvider, Regions.getRegion(Regions.SELECT_YOUR_REGION));
            File fileToUpload = YOUR_FILE;
            //(Replace "MY-BUCKET" with your S3 bucket name, and "MY-OBJECT-KEY" with whatever you would like to name the file in S3)
            PutObjectRequest putRequest = new PutObjectRequest("MY-BUCKET", "MY-OBJECT-KEY",
                        fileToUpload);
            PutObjectResult putResponse = s3Client.putObject(putRequest);

            GetObjectRequest getRequest = new GetObjectRequest("MY-BUCKET", "MY-OBJECT-KEY");
            S3Object getResponse = s3Client.getObject(getRequest);
            InputStream myObjectBytes = getResponse.getObjectContent();

            // Do what you want with the object
            
            myObjectBytes.close();

            return null;
        }
}`

**Comment by raphkim** [comment]
Would you be able to check the following?

1.  Go to AWS Cognito console -> Manage Identity Pools
2. Select the identity pool linked to your app
3. Click "Edit identity pool"
4. Check which roles are attached as "Authenticated role" and "Unauthenticated role"
5. Go to AWS IAM console -> Access Management -> Roles
6. See the details of the roles identified earlier
7. Verify that they contain the appropriate [user/bucket policies for S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-overview.html)

**Comment by raphkim** [comment]
Also I would strongly advise you to use the [latest SDK version](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.11) as there have been many bug fixes and other improvements over time.
