### ISSUE TITLE
Getting this error on signup result what am i doing wrong ?

### ISSUE THREAD

**Issue by Nakuls426** [aws-amplify/aws-sdk-android#1597]
Sign up failed: **java.lang.NullPointerException:** Attempt to invoke virtual method 'void com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool.signUp(java.lang.String, java.lang.String, com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserAttributes, java.util.Map, com.amazonaws.mobileconnectors.cognitoidentityprovider.handlers.SignUpHandler)' on a null object reference

**Comment by raphkim** [comment]
Hi @Nakuls426 ,

Thank you for reaching out to us. Unfortunately, we are going to need a little more information in order to better assist you. Would you be able to provide the code snippet that caused this error to be reported? The NPE suggests that your user pool instance is `null` at the time of sign up invocation. Are you correctly instantiating a `CognitoUserPool` instance by providing it with context and `AWSConfiguration` object?
