### ISSUE TITLE
 showSignIn called with HostedUI options in awsconfiguration.json

### ISSUE THREAD

**Issue by sagarkhurana00786** [aws-amplify/aws-sdk-android#1642]
Getting this error when Using Google sign in in Android AWS amplify

`E/OAuth2Client: onError: 
    java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json
        at com.amazonaws.mobile.client.AWSMobileClient$23.run(AWSMobileClient.java:2684)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:760)`

Please help thanks

**Comment by imekinox** [comment]
@sagarkhurana00786 how did you solved it?

**Comment by samk17cmutpm** [comment]
Has the same problem. AmplifyException {message=Sign in with web UI failed, cause=java.lang.Exception: showSignIn called with HostedUI options in awsconfiguration.json, recoverySuggestion=See attached exception for more details}

How to solve it????

**Comment by jc-delvalle** [comment]
In my case it was that I enabled ProGuard and didn't added the pro-guard rules defined here:
https://github.com/aws-amplify/aws-sdk-android/blob/master/Proguard.md

**Comment by M9Apar** [comment]
its not working

**Comment by WassimErriha** [comment]
Same here

**Comment by AlbertoSinigaglia** [comment]
news???

**Comment by richardmcclellan** [comment]
@AlbertoSinigaglia this looks like a duplicate of https://github.com/aws-amplify/amplify-android/issues/1181 (the one you already opened today), which is also a duplicate of https://github.com/aws-amplify/amplify-android/issues/1066.

If you want to use HostedUI and you don't have "OAuth" in your `amplifyconfiguration.json`, it means you didn't select the right options during `amplify add auth`.  You can solve this by running `amplify update auth`.   Then, when asked `Do you want to use the default authentication and security configuration?`, choose `Default configuration with Social Provider (Federation)`

**Comment by AlbertoSinigaglia** [comment]
@richardmcclellan the point is that i don't want social login, i want to login using Cognito with the usual "username-password"

**Comment by richardmcclellan** [comment]
Hi @AlbertoSinigaglia, there are 3 supported sign in methods:

1. `signIn` (username - password sign in through a 
2. `signInWithWebUi` (username - password sign in through a hosted UI webview) 
3. `signInWithSocialWebUi` - (sign in with Google, Facebook, etc)

For (1), you need to choose "Default Configuration"
For (2) or (3), you need to choose "Default configuration with Social Provider (Federation)".  Admittedly, the wording is probably a little confusing, since (2) is not a _social_ provider.

Note that we don't currently support (1) AND (2) or (3) in the same app.  Please comment or add a reaction on [this feature request](https://github.com/aws-amplify/amplify-android/issues/1180), if that's something you want.

**Comment by emanduprat-chwy** [comment]
It happened to me when I tried to launch hostedUI before calling AWSMobileClient.getInstance().initialize, hope this helps you.
