### ISSUE TITLE
TransferUtility does not implement onDowngrade for SQL

### ISSUE THREAD

**Issue by blainekasten** [aws-amplify/aws-sdk-android#1872]
**Describe the bug**

I'm currently trying to use the `TransferUtility` to download a file. When I do, I get an SQL exception that says "cannot downgrade from 6 to 5". According to [this StackOverflow answer](https://stackoverflow.com/a/43466872), this bug occurs because ya'll haven't implemented the `onDowngrade` API for your [`TransferDatabaseHelper`](https://github.com/aws-amplify/aws-sdk-android/blob/8c69cb0f9626e42301e32984262fbadaa3ba14f6/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferDatabaseHelper.java#L22). 

**To Reproduce**

I'm not sure if there is anything specific needed for setup in order to trigger this. I am running this in a simulator for a Pixel XL, API 29.

```java
TransferUtility transferUtility = TransferUtility.builder()
    .context(context)
    .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
    .s3Client(s3Client)
    .build();
TransferObserver downloadObserver =
    transferUtility.download(key, new File(id + ".wav"));
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.6.+
 - Device: Pixel XL API 29
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: IDK

**Comment by raphkim** [comment]
Hi @blainekasten ,
Is there a specific reason why you are using the SDK version 2.6? We are currently on [2.16.12](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.12), which contains many fixes and improvements.

The shape of database for storing transfer information has been modified since that version, which is why you are experiencing this failure. The best fix for this would be to upgrade to the latest version of the SDK.

Another workaround that I do NOT recommend is to delete the existing transfer table "awss3transfertable.db" and letting `TransferUtility` recreate it from scratch rather than attempt to downgrade. However, its purpose is to track ongoing transfers persistently, and deleting it will cause all of that information to be lost.
