### ISSUE TITLE
Support IPv4 fallback

### ISSUE THREAD

**Issue by Shay-repos** [aws-amplify/aws-sdk-android#2105]
Currently, if the user's network does not support IPv6, then there's no way to connect to AWS IoT. Android would prefer IPv6 to IPv4.

Please add a fallback for IPv4, or provide an option to explicitly specify which protocol to use.

**Comment by jamesonwilliams** [comment]
Likely, this will require support in Paho, too. See related: https://github.com/eclipse/paho.mqtt.android/issues/385.

**Comment by shawzyen** [comment]
Hi, @Shay-repos have you found a solution to this issue?

I have no idea why such a fundamental feature hasn't add to the Android SDK. Ios and Android Simulator can connect to AWS IoT smoothly, can't connect to AWS IoT in Ipv4-only environment is disastrous for android device

**Comment by Shay-repos** [comment]
I had to modify the SDK to bypass domain checking and passed in IPv4 of aws endpoint. 
Not optimal solution though.

**Comment by shawzyen** [comment]
@Shay-repos Great idea. Your method seems to be the most effective so far.  I had tried to modify the Android SDK as what you said, but get an error:
>MqttException (0) - javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match

Could you teach me how to bypass domain checking, please? This issue has been bothering me for weeks

**Comment by Shay-repos** [comment]
There is a private field named "endpoint" in class AWSIotMqttManager. I just changed it to public and set it to IPv4 string right after creating new AWSIotMqttManager instance.

**Comment by jamesonwilliams** [comment]
@Shay-repos There are [constructors which accept an `endpoint`](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.html#AWSIotMqttManager-java.lang.String-java.lang.String-). You should be able to set that field directly when you construct the `AWSIotMqttManager`, instead of using reflection as you propose.

**Comment by shawzyen** [comment]
Hi @jamesonwilliams, could you modify endpoint from private to public, or modify private AWSIotMqttManager(final Region region, final String mqttClientId, final String endpoint) to public in AWSIotMqttManager.java, please? So that we could force the android device to connect to the server in IPv4.

**Comment by jamesonwilliams** [comment]
@shawzyen Did you see [my comment, here](https://github.com/aws-amplify/aws-sdk-android/issues/2105#issuecomment-713891719)? Can't you use [this version](https://github.com/aws-amplify/aws-sdk-android/blob/129e33340909b3499771c19a4ea2dea0747724f5/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L660-L670)?

**Comment by Shay-repos** [comment]
> @Shay-repos There are [constructors which accept an `endpoint`](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.html#AWSIotMqttManager-java.lang.String-java.lang.String-). You should be able to set that field directly when you construct the `AWSIotMqttManager`, instead of using reflection as you propose.

Constructor has region checking, it will throw error if endpoint is IP Address

**Comment by jamesonwilliams** [comment]
@Shay-repos Can you use [this factory method](https://github.com/aws-amplify/aws-sdk-android/blob/129e33340909b3499771c19a4ea2dea0747724f5/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L761-L772)?
```kotlin
val region = Region.getRegion(Regions.CN_NORTH_1)
val endpoint = Endpoint.fromString("....")
val clientId = ClientId.fromString("....")
val iotManager = AWSIotMqttManager.from(region, clientId, endpoint)
```

**Comment by Shay-repos** [comment]
@jamesonwilliams oh thanks, that worked.

**Comment by shawzyen** [comment]
@Shay-repos Hi Shay, did you add the IP address in the certificate's Subject Alternative Name list? I have tried to connect to the server in IPv4 address, and it throws an error:
>MqttException (0) - javax.net.ssl.SSLHandshakeException: No subjectAltNames on the certificate match
It seems caused by the certificate, but I'm not sure.

**Comment by jamesonwilliams** [comment]
@shawzyen If I understand that error correctly:

The certificate lives on an AWS IoT endpoint, and can't be modified by you, the customer. A Subject Alternate Name on a certificate basically says ("In addition to my real name `system.whatever.com`, you can refer to me as `123.44.66.19`, if you'd like.) However, the IP addresses of the endpoint is probably not listed in the SAN portion of the SSL certificate, since AWS would need to frequently invalidate the certificate, when the IP set changes.

A client can theoretically disable SAN validation, though. Some discussion on achieving that with Paho, here: https://github.com/eclipse/paho.mqtt.java/issues/341. At first glance, the AWS IoT SDK doesn't have a pathway to achieve this, at the moment.

**Comment by shawzyen** [comment]
@jamesonwilliams Thanks for your reply. That's pretty much what I thought it would be, But I am curious how does @Shay-repos connect to the server in IP address?

**Comment by shawzyen** [comment]
Hi @Shay-repos, did you connect to the endpoint with IPv4 address successfully? After tried the serval method but got all failed, I doubt whether this method is feasible.  I am glad if you could give me some advice, thank you!

**Comment by rjuliano** [comment]
Original issue resolved.

**Comment by andrej-vasilj** [comment]
Why is this issue closed? I am currently facing this issue and I'm wondering what the solution is?
