### ISSUE TITLE
Does AWS Android SDK support non-Cognito IAM authorization?

### ISSUE THREAD

**Issue by michaelyfan** [aws-amplify/aws-sdk-android#2211]
**State your question**
I am following the documentation at https://docs.amplify.aws/sdk/api/rest/q/platform/android#iam-authorization. I have an old app that is utilizing AWS SDKs from 2017, and we would like to add a REST API that the app can use. This isn't a new app, so we're not using AWS Amplify, instead we are using the AWS Android SDKs (which are also documented on the Amplify site).

If I follow the documentation to push and use a REST API, I am met with the `Cognito Identity not configured (Service: null; Status Code: 0; Error Code: null; Request ID: null)` error. But I'm confused; _must_ I utilize user pools, and log-ins and log-outs? The documentation under the section "IAM authorization" seems to imply that it is an alternative to authorization based on Cognito User Pools. I expected to just give it an API key and secret, and be able to access the API.

Before you come at me about security issues, keep in mind that certain...circumstances...allow us to be lax with the security for now. We just want to get a demo up. 

The documentation _does_ state that "For AWS IAM authorization use the `AWSMobileClient` as outlined in the [authentication section](https://docs.amplify.aws/sdk/auth/getting-started/q/platform/android)". Unfortunately, this is pointless, as the linked authentication section does not contain any documentation at all regarding IAM authorization without Cognito. See for yourself.

**Which AWS Services are you utilizing?**
REST API

**Provide code snippets (if applicable)**
All applicable code snippets mimic the documentation linked to earlier.

**Environment**
 - SDK Version: 2.6.3

**Device Information**
 - Device: Pixel 2 Emulator
 - Android Version: 8.1

**Comment by raphkim** [comment]
Hi @michaelyfan ,

Thank you for your interest in using our SDK! I have looked at the docs and have noticed the use-case is indeed under-documented. I will bring it up with the team to see if we could make any improvements.

Meanwhile, please try using `ApiClientFactory#apiKey(String)` method to configure it with an API key rather than using `ApiClientFactory#credentialsProvider(AWSCredentialsProvider)` if you would prefer to use API key instead of IAM or Cognito. This will add a header containing the supplied API key to any request being sent out by the client to authorize it.

p.s. I would still like to encourage you to consider adopting the Amplify Framework in your app :)
