### ISSUE TITLE
createMediaSource api consume a lot of time

### ISSUE THREAD

**Issue by Ranchee** [aws-amplify/aws-sdk-android#2221]
**State your question**
I'm using Kinesis Video Android SDK. And I find that `createMediaSource` API
takes a lot of time.  After debuging, I found that the `createStreamSync` API
is the main reason. It'll cost 4-5s on my side.

[Here's the code](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/kinesisvideo/internal/client/NativeKinesisVideoClient.java#L148).

I printed the timestamp before and after the `createStreamSync` API. The log
shows it takes 4-5 seconds to complete.

I have two questions:
1. Why does the `createStreamSync` API take so much time？Can we reduce it?
2. I found another api: `createStream`. Can I replace `createStreamSync` with
   `createStream`? Are there any effects?

**Which AWS Services are you utilizing?**
Kinesis Video Android SDK

**Environment(please complete the following information):**
`aws-android-sdk-kinesisvideo:2.19.1`, Android Platform

**Comment by raphkim** [comment]
Heya @Ranchee ,
I will pass this along to the Kinesis Video service team to see what could be causing the delay. Thank you!

**Comment by Ranchee** [comment]
Hi @raphkim  Any update about this ?

**Comment by lawmicha** [comment]
Hi @Ranchee, since this is a pretty old issue, were you able to investigate further into why this was happening for you and if you were able to resolve this? If you are still looking for resolution, can you provide us with some debug info on Network Inspector to show that this is an issue on the service request and not something in the client? With that and the request Id we should be able to ask Kinesis team if this is an expected response SLA.
