### ISSUE TITLE
AWSIotMqttManager autoReconnect is not working

### ISSUE THREAD

**Issue by OKatrych** [aws-amplify/aws-sdk-android#2360]
**Describe the bug**
When there is no internet connection and `autoReconnect` is set to `true`, then calling the 
`connect(credentialsProvider, statusCallback)` returns the `AWSIotMqttClientStatus.ConnectionLost` but does not schedule reconnection.

**To Reproduce**
1. Create client:
```
val client = AWSIotMqttManager(token, environment.iotUrl).apply {
    keepAlive = 10
    setReconnectRetryLimits(5, 15)
    isAutoReconnect = true
    maxAutoReconnectAttempts = -1
    setCleanSession(false)
    connectionStabilityTime = 10
    isOfflinePublishQueueEnabled = false
}
```
2. Try to connect:
```
client.connect(credentialProvider) { status, _ -> 
    Log.d(status)
}
```

The problem is inside `connect(credentialsProvider, statusCallback)` method, when credentials provider `getCredentials()` is called it throws an exception, but inside `catch (final MqttException e)` there is no reconnection logic. 

**Which AWS service(s) are affected?**
IoT

**Expected behavior**
In my opinion, `connect(credentialsProvider, statusCallback)` should have the same reconnection logic as `mqttConnect(MqttConnectOptions options)` method has:
```
if (!userDisconnect && autoReconnect) {
    connectionState = MqttManagerConnectionState.Reconnecting;
    sessionPresent = asyncActionToken.getSessionPresent();
    userConnectionCallback(e);
    scheduleReconnect();
} else {
    connectionState = MqttManagerConnectionState.Disconnected;
    sessionPresent = asyncActionToken.getSessionPresent();
    userConnectionCallback(e);
}
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.22.1
 - Device: Any android device
 - Android Version: Any version
 - Specific to simulators: No

**Comment by lawmicha** [comment]
Hi @OKatrych, thanks for opening this issue and the detailed explanation. Since this has been opened for awhile now, can you let us know if you still need this change? Were you able to make any workarounds such as a retry mechanism from your end? 

Based on your description, we would be making changes to the error handler in this code https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L959-L1033 when catching the MqqtException here https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L1023-L1025 we could do some internal retry based on `autoReconnect` config being set.
