### ISSUE TITLE
AmazonCognitoAuthDemo code base access

### ISSUE THREAD

**Issue by kuabhish** [aws-amplify/aws-sdk-android#2369]
Hello, 

I want to access this old code bases:
 [cognition auth demo old](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoAuthDemo)
&
[user pool auth demo](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo)

Please help.

**Comment by richardmcclellan** [comment]
Hi @kuabhish, these sample apps were [recently removed](https://github.com/awslabs/aws-sdk-android-samples/pull/342), as they are out of date, and don't represent the recommended approach for using Cognito now.  Instead, I'd suggest evaluating the [Auth category](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android) of the Amplify Android library.  

If you do still want to access these repos, you can find them in the Git history, here:
 - [AmazonCognitoAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/5d86bccc90d264be6c6619647db6761edf21fccd/AmazonCognitoAuthDemo)
 - [AmazonCognitoYourUserPoolsDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/5d86bccc90d264be6c6619647db6761edf21fccd/AmazonCognitoYourUserPoolsDemo)

Lastly, could you tell me where you found the links to these old sample apps?  I'd like to update them, since they are obviously broken now.

**Comment by kuabhish** [comment]
@richardmcclellan

[AmazonCognitoUserpoolsDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/5d86bccc90d264be6c6619647db6761edf21fccd/AmazonCognitoYourUserPoolsDemo)

This is not broken. It's working too well for me.

When I was writing the code for SingUp, Sign In, etc. I was unable to work with amplify, so I used this repo.

In short few months back I was unable to work around amplify. So I used this repo and it helped me a lot. I wanted to change my auth from (username, password)
to google auth.. so I was looking for 
https://github.com/awslabs/aws-sdk-android-samples/tree/5d86bccc90d264be6c6619647db6761edf21fccd/AmazonCognitoAuthDemo

**Comment by richardmcclellan** [comment]
> Thanks a lot @richardmcclellan

Sure!

> This is not broken. It's working too well for me.

I didn't mean the _sample apps_ were broken, I meant the _links_ that you shared ([CognitoAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoAuthDemo) and [UserPoolAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo)) are broken.  Can you share where you found those links?

**Comment by kuabhish** [comment]
I didn't find them anywhere ... I had saved them .. long back ..
