### ISSUE TITLE
RemoteServiceException when start TransferService from a Service

### ISSUE THREAD

**Issue by buntupana** [aws-amplify/aws-sdk-android#2471]
**Describe the bug**
Sometimes I get a RemoteServiceException starting TransferService from a Service. Cant reproduce the error because I got it from users, never experimented myself

The exception: 

```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6971a94 u0 com.example.app/com.amazonaws.mobileconnectors.s3.transferutility.TransferService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**To Reproduce**
```
val tsIntent = Intent(this, TransferService::class.java)                                  
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {                                     
    tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION, uploadNotification.build())
    tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, NOTIFICATION_ID)        
    tsIntent.putExtra(TransferService.INTENT_KEY_REMOVE_NOTIFICATION, true)               
    startForegroundService(tsIntent)                                                      
} else {                                                                                  
    startService(tsIntent)                                                                
    startForeground(NOTIFICATION_ID, uploadNotification.build())                          
}      
```                                                                                   

**Which AWS service(s) are affected?**
com.amazonaws:aws-android-sdk-s3

**Expected behavior**
Start the TransferService as usual

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.22.2
 - Device: Mostly Samsung
 - Android Version: > Oreo

**Comment by buntupana** [comment]
???

**Comment by matale** [comment]
This is seems to be an Android issue, startForeground has to be called within 5 seconds of starting a foreground service from the background but the OS can not guarantee this will happen, even if you do nothing between the 2 sometimes it will take longer than 5 seconds.  

You can try minimize the amount of work between the two, eg move the notification stuff into the service onStartCommand don't pass/parse extras  but still it will happen now and then.
You can also take a look at this for some more ideas 
https://github.com/gotev/android-upload-service/issues/549#issuecomment-819070566

Solution seems to be if you are starting the service from the foreground when user is using App then call startService instead of startServiceForeground.  This still rill run as a foreground service and seems to survive killing of the App.

If you actually need to start the service from the background when app is not visible then moving to WorkManager seems to be the way to go.

**Comment by gpanshu** [comment]
Closing as per the last comment. Thank you.
