### ISSUE TITLE
Getting many Non-fatal exceptions in firebase Crashlytics.

### ISSUE THREAD

**Issue by shiv71** [aws-amplify/aws-sdk-android#2515]
**State your question**
Getting many Non-fatal exceptions in firebase Crashlytics.

**Which AWS Services are you utilizing?**
AWS Android SDK (AWSTransferUtility)
```gradle
implementation('com.amazonaws:aws-android-sdk-mobile-client:2.20.+@aar') { transitive = true }
implementation 'com.amazonaws:aws-android-sdk-s3:2.20.+'
```
**Environment(please complete the following information):**
 - SDK Version: [2.20]

**Device Information (please complete the following information):**
 - Devices: [Galaxy S20 5G,Galaxy S10+,Galaxy S20 Ultra 5G,Galaxy A71 5G,LG Stylo 5,motorola edge plus and many more]
 - Android Version: [11,9]

In the past 90 days approx 14 users got this Non-fatal exception event approx 50 times. We also do not know how we can troubleshoot/reproduce this. Please find the crash logs attached.
[crash_logs.log](https://github.com/aws-amplify/aws-sdk-android/files/6656355/crash_logs.log)

**Comment by richardmcclellan** [comment]
Hi @shiv71, from your logs, it looks like some of the requests are timing out, probably due to devices having poor or no internet connection.

I'd suggest handling errors like that reported from TransferUtility by displaying an alert to your users saying there is a problem with the network connection, and they should retry once their device has a connection again.
