### ISSUE TITLE
Wrong progress calculation/notification when resuming large multipart upload 

### ISSUE THREAD

**Issue by MishalJariwala** [aws-amplify/aws-sdk-android#2601]
I'm using the TransferUtility class to upload files to Amazon s3 using
TransferUtility.upload() or TransferUtility.resume() in case of
interruption, and using TransferObserver.setTransferListener() to listen for
upload progress.

If I upload a large file (let's say 100MB) using multipart upload without any
interruption , then the current progress of the upload is calculated and
dispatch correctly with the right value every period.

However, if the upload is interrupted for some reason after 50% of successfully
uploaded parts, and then resumed, the current progress of the upload is
calculated incorrectly. It will not notify the listener until the
totalBytesTransferred after resume > prevTotalBytesTransferred before interruption(that already uploaded before), which is a
wrong calculation in the case of a resumed upload.

The calculation is made inside the UploadTaskProgressListener of the
UploadTask class. I think the issue could be fixed there.

**Environment:**
2.29.0

**Device Information:**
Oneplus Nord
Android 11

**Comment by rjuliano** [comment]
Related to #2269

**Comment by MishalJariwala** [comment]
@rjuliano Is there any more data you need from my side to help?

**Comment by MishalJariwala** [comment]
@rjuliano Any update on this?

**Comment by Huangweijia100** [comment]
I thinks is wrong when get "totalBytesTransferredOfAllParts" in onProgressChanged()[UploadTaskProgressListener.class],Because totalBytesTransferredOfAllParts is the sum of the task in all uncomplete tasks.so when their sum is greater than "prevTotalBytesTransferredOfAllParts",the updateProgress will be called.I think it is possible to use   the sum of current part fileOffset and bytesTransferredSoFar instead of totalBytesTransferredOfAllParts?

**Comment by MishalJariwala** [comment]
@sdhuka @eeatonaws Any update or workaround on this bug?

**Comment by MishalJariwala** [comment]
@sdhuka @eeatonaws Please look into this issue if possible as soon as possible.

**Comment by MishalJariwala** [comment]
Thank you for the fix!
