### ISSUE TITLE
Failed resolution of kinesisfirehose service

### ISSUE THREAD

**Issue by tyagi-bhoopesh** [aws-amplify/aws-sdk-android#2624]
I am getting the below error.
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amazonaws/services/kinesisfirehose/model/PutRecordBatchRequest;

These are sdk details:
compileSdkVersion 30
buildToolsVersion "30.0.3"

and current version of service: 
implementation 'com.amazonaws:aws-android-sdk-kinesis:2.30.0'

**Comment by rjuliano** [comment]
Strange. The [latest change](https://github.com/aws-amplify/aws-sdk-android/commit/a928da73e5694b46e9822081faa3553c0b10e619#diff-f30ae4b33d7f9f67d731118ec2de24671cd7ca964e4a2dd7f3393534df7a331a) to the file only updated comments.

Do you have a stack trace or sample code you can share?

**Comment by raphkim** [comment]
Hi @tyagi-bhoopesh ,

We suggest using simple troubleshooting steps for build errors such as:
1. Invalidate cache and restart IDE
2. try `./gradlew clean build` in project route

If above steps did not fix the issue, then please feel free to share your code snippets so that we can look further into this issue. Thank you!
