### ISSUE TITLE
kinesisvideo below SDKVersion 24

### ISSUE THREAD

**Issue by prechtelm** [aws-amplify/aws-sdk-android#2630]
Hi, 
am I really locked to version 2.18.0 if I want to use kinesisvideo below SDKVersion 24?! 
Please advise how to use latest versions of the SDK in that use case.

**Which AWS Services are you utilizing?**
- com.amazonaws:aws-android-sdk-kinesis
- com.amazonaws:aws-android-sdk-kinesisvideo
- com.amazonaws:aws-android-sdk-kinesisvideo-signaling

**Environment(please complete the following information):**
 - SDK Version: 2.18.0

**Comment by changxu0306** [comment]
The latest version of SDK is 2.31.0. Can you elaborate on your question?

**Comment by raphkim** [comment]
Hey @hassanctech,
Would you be able to elaborate on the decision to raise the minSDK of `kinesisvideo` SDK to 24 and how our customers can work around it on older devices?

**Comment by hassanctech** [comment]
If you see the comment here:

https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-kinesisvideo/build.gradle#L9

It's references the X509ExtendedTrustManager interface which we needed for hostname verification (well unless we wanted to write it ourselves), this was added in 24 hence we upgraded the min version to 24.  

Unfortunately right now due to its requirement for implementation I do not know of a way around it.

**Comment by gpanshu** [comment]
@prechtelm I understand that you are not satisfied with the answer but due to platform changes that we are dependent on this change was mandatory. You can continue using the older version of the SDK but we always recommend updating to the latest versions.
