### ISSUE TITLE
IOT Connection - java.lang.IllegalArgumentException: no NetworkModule installed for scheme “ssl” 

### ISSUE THREAD

**Issue by hardikdevios** [aws-amplify/aws-sdk-android#3356]
**Describe the bug**
After updating the AWS SDK Library to 2.71.0 I am getting the following exception from **mqttManager?.connect()** function

**java.lang.IllegalArgumentException: no NetworkModule installed for scheme “ssl” of URI “ssl://xxxxxxxxxxxxxx-xxx.iot.xx-xxxx-1.amazonaws.com:8883”**

**Which AWS service(s) are affected?**
AWS IOT

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.71.0
 - Device: Pixel 4a
 - Android Version: Pie 9.0
 - Specific to simulators: No

**Comment by tylerjroach** [comment]
@hardikdevios This looks like it is coming from the Paho client. Can you try these proguard rules? 
https://github.com/eclipse/paho.mqtt.java/issues/572#issuecomment-641083671

**Comment by hardikdevios** [comment]
> @hardikdevios This looks like it is coming from the Paho client. Can you try these proguard rules? [eclipse/paho.mqtt.java#572 (comment)](https://github.com/eclipse/paho.mqtt.java/issues/572#issuecomment-641083671)

Thank you, let me try it

**Comment by hardikdevios** [comment]
@tylerjroach Proguard rules didn't work, still getting the same error

**Comment by hardikdevios** [comment]
@tylerjroach Any idea, do we require any other proguard rules to get it working?

**Comment by hardikdevios** [comment]
@tylerjroach Any way solved the issue, so I am closing the ticket

**Comment by tylerjroach** [comment]
Sorry I had not gotten back to you yet but I am glad you resolved the issue. If there are any details that you can share, in case another customer runs into the same issue, it would be appreciated. Thanks!

**Comment by F1nny** [comment]
Thanks @tylerjroach for your help here, it appears that in the newer AWS SDK, the paho client SPI NetworkModuleFactory is now created as a service in the Android META-INF which was not the case in the prior versions (we hadn't updated since last year so was a bit of a jump). Due to some other factors our apk has to be resigned via command line which has always cleared the META-INF before resigning, and losing that service file is what caused the problem :smile: After reworking the resigning process, we're back to normal :tada: Thanks again!
