### ISSUE TITLE
How to upload to s3 with endpoint URL

### ISSUE THREAD

**Issue by chandangit89** [aws-amplify/aws-sdk-android#3517]
**State your question**

**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by chandangit89** [comment]
I tried all the documented methods in your website but couldn't succeeded, I have a endpoint URL, access key, security key, bucket name  only.
i do not have dashboard access so how to give policy required to upload from mobile, whole lot of issues but i couldnt find any solution from your documentation

**Comment by mattcreaser** [comment]
Hi @chandangit89, could you please be more specific about your error? What happens when you try to upload the file? Can you show a code snippet?

This issue is posted in the AWS SDK for Android - unless you are already heavily invested into this SDK I would also strongly recommend using the much newer [Amplify V2](https://github.com/aws-amplify/amplify-android) ([docs](https://docs.amplify.aws/android/tools/libraries/)) instead.

You will need to have a policy set up to allow file upload access. It's not specific to a particular platform, but the identity performing the operation will need permission.
