### ISSUE TITLE
Using Pinpoint for event-driven user-specific mobile push notifications (eg. "Jane liked your post") 

### ISSUE THREAD

**Issue by ajhool** [aws-amplify/aws-sdk-android#450]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Pinpoint or AWS SNS

* In what version of SDK are you facing the problem?
N/A

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/). 

The issue is in regards to the documentation.

Mobilehub and the Android SDK seem to prioritize Pinpoint over SNS for mobile push notifications. However, the Pinpoint documentation is unclear about the very common use-case of pushing a notification to a specific user. For instance, in a photo sharing app, a common notification would be "SomeSpecificUser just liked YourSpecificPost". Is Pinpoint the correct tool for that or does SNS->GCM/FCM/APNS remain the appropriate solution?

It is unclear if the class:
 `com.amazonaws.services.pinpoint.model.EndpointUser;`
represents a specific User or a prototypical user that would be used to select matching users when creating a demographic/campaign.

Pinpoint offers convenient device token + cognito user management, so it would seem to be a preferable approach to SNS.

**Comment by kvasukib** [comment]
Thank you @ajhool for reporting to us. Sorry for the inconvenience caused.

Amazon Pinpoint and Amazon SNS have overlapping feature sets, with Amazon Pinpoint being the recommended service for user engagement scenarios, such as the one you have described. Amazon Pinpoint lets you send messages to end-users in two primary ways, through campaigns and direct sends. Campaigns are valuable when you want to leverage messaging variables, targeting, scheduling, and automation features of Amazon Pinpoint. Direct sends is valuable when you have a one-to-many or transactional use case, where the analytics on the message sends aren’t as important. More information on Campaigns can be found [here](https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-campaigns.html) and more information on Direct sends can be found [here](https://docs.aws.amazon.com/pinpoint/latest/apireference/rest-api-messages.html).

**Comment by muellerfr** [comment]
Hi @ajhool,

Direct send is a feature request for the Pinpoint service. We're taking this to the Pinpoint team, and will report back on this thread if there are any updates.

**Comment by kvasukib** [comment]
@ajhool The event based trigger feature has been released: https://aws.amazon.com/blogs/messaging-and-targeting/event-based-campaigns-let-you-automatically-send-messages-to-your-customer-when-they-perform-certain-actions/

Event-based campaigns help you send messages that are timely, personalized, and relevant to your customers, which ultimately increases their trust in your brand and gives them a reason to return.

When you use the campaign wizard in the Amazon Pinpoint console, you now have the option to create event-based campaigns. Rather than define a time to send your message to customers, you select specific events, attributes, and metric values. 

To report events from your Android application, you can use the following guide: https://aws-amplify.github.io/docs/android/analytics

**Comment by returnzer0** [comment]
How would one go about mapping cognito id to an endpoint to send push messages to a specific user? I see that there is documentation for using pinpointAppId for setting up cognito, but it doesn't register the device ID instead it uses the email as a channelType. Is there any other way to send notifications to a specific user?

**Comment by joebernard** [comment]
@returnzer0 Were you able to figure out how to send a push notification to a Cognito user? Right now I'm storing the device token and Cognito ID (sub) in a database, then looking up the token when I send the push.

The documentation around this is lacking and none of the responses in the thread answer how to do this.

**Comment by returnzer0** [comment]
@joebernard yes I did.

Its a 3 step process on my part.
Frontend:
1. [Register the endpoint with the Cognito ID.](https://aws-amplify.github.io/docs/ios/analytics#registering-endpoints-in-your-application)

Backend:
2. [Given a Cognito ID, find all of the registered endpoints.](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#getUserEndpoints-property)
3. [Send message to the specific endpoint.](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Pinpoint.html#sendMessages-property)

**Comment by kvr2277** [comment]
Is there a way to schedule notification to single user/single endpoint? Currently what I'm aware is that we need to create campaigns to schedule notifications in future. If there's a way to schedule notifications (say send a push notification to user after 1 hour from now reminding him to check the app again etc)

**Comment by magicmove** [comment]
Hi there, 

Love AWS but the "push notifications to specific Cognito user" part is killing too much of my time.
Finally got my notification with the following method: 

1. Update analytics endpoint `Analytics.updateEndpoint({...UserId: user._id,...})`
2. Trigger a lambda to send a notification using the Cognito user id 

The problem is that I still receive the notifications even when I log out. 
Now I am trying to update the endpoint UserId attribute when the user logs out with 
`Analytics.updateEndpoint({...UserId:  "0"...})` 
but nothing is working. Its too hard to test and have no documentation on that part... 

Can someone tel me if there is a more solid solution in 2021 ?

Thanks !
