### ISSUE TITLE
S3:Check if upload is completed successfully or not?

### ISSUE THREAD

**Issue by shivam21** [aws-amplify/aws-sdk-android#643]
**State your question**
How to Check if upload is completed as transferUtility.resume(awsid) returns null?

**Which AWS Services are you utilizing?**
S3
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
2.10.0
**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:
All Devices

**Comment by kvasukib** [comment]
@shivam21 Thank you for reporting to us. Sorry for the inconvenience caused. `resume` can return null when the transfer record identified by the transfer id passed in cannot be found in the SQL database (persistent store).

It could be due to one of the following reasons:
1) The transfer is completed and the record is removed from the database. Can you check if the object is uploaded and available on S3? If so, I suspect you are resuming a transfer that is already completed.
2) The device could be running low on memory and the database operations could have been failing. 

I suspect (1). Can you verify?

**Comment by shivam21** [comment]
@kvasukib Thanks for the quick reply.yes you are right transfer is completed but i want to delete the file(in local) afterwards but before deleting file(local) i want to make sure it is uploaded successfully.is there any way by which i can prevent transferutility to delete the record itself(after completion of upload)

**Comment by kvasukib** [comment]
@shivam21 The `TransferUtility` always deletes the transfer record when the transfer is completed. This is the behavior of the `TransferUtility` as not deleting them would cause the database size to grow. To know if the transfer has been completed successfully, you can rely on the following information:

1) `onStateChanged` callback in `TransferListener`
2) `onProgressChanged` callback in `TransferListener`
3) Check if the object exists on S3:

```java
if (amazonS3Client.doesObjectExist(bucket_name, object_name)) {
  Log.i("Object successfully uploaded.");
}
```

**Comment by shivam21** [comment]
@kvasukib ok thanks.will give it a try.
