### ISSUE TITLE
Deadlock when retrieving tokens which are invalid

### ISSUE THREAD

**Issue by dbathily** [aws-amplify/aws-sdk-android#659]
**Describe the bug**

After `AWSMobileClient.initialize`, I'm trying to get the user's tokens which are now invalid with `AWSMobileClient.getTokens(callback)`, expecting a call on the callback `onError`. Instead I get a deadlock, nothing happens.

When following the calls, the problem come from `waitForSignIn`. The `userStateDetails.getUserState` is `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` which cause `                    mSignedOutWaitLatch.await();` to be called

```
                case SIGNED_OUT_FEDERATED_TOKENS_INVALID:
                    mSignedOutWaitLatch.await();
                    return getUserStateDetails(false).getUserState().equals(UserState.SIGNED_IN);
```

**Which AWS service(s) are affected?**

Cognito

**Expected behavior**

`AWSMobileClient.getTokens(callback)` should call `callback.onError` when tokens are invalid
**Environment(please complete the following information):**
 - SDK Version: 2.9.+

**Comment by palpatim** [comment]
@dbathily

Thanks for reporting this issue. We'll investigate and update this thread when we have more information.

**Comment by minbi** [comment]
Hi @dbathily ,

This is the expected behavior. This lock provides the developer a chance to refresh the session before retrieving expired tokens. The `releaseSignInWait` method can be called to release the lock and exhibit the expected behavior noted in your post.

We are tracking this documentation issue here https://github.com/aws-amplify/docs/issues/414

**Comment by dbathily** [comment]
Thank you for your input @minbi I get it now
