### ISSUE TITLE
S3 with Cognito (CognitoCachingCredentialsProvider) is not renewing access token.

### ISSUE THREAD

**Issue by k-thorat** [aws-amplify/aws-sdk-android#671]
**Describe the bug**
We are using S3 with CognitoCachingCredentialsProvider, It works fine until access token is active. Once expired (1 hour) Throws exception on any activity on TransferUtility. 
**{"__type":"NotAuthorizedException","message":"Invalid login token. Token expired: 1548215704 >= 1548214608"}**

**To Reproduce**
1. Create TransferUtility with S3Client (CognitoCachingCredentialsProvider) and Default settings
2. Download/Upload S3 resources
3. Wait for access token to expire (1 hour)
4. Try to Download/Upload S3 resource
5. TransferListener Throws Exception

**Which AWS service(s) are affected?**
S3, Cognito

**Expected behavior**
CognitoCachingCredentialsProvider renews token or after using clear/clearCredentials get's new token.

**Environment(please complete the following information):**
 - SDK Version: 2.11

**Device Information (please complete the following information):**
 - Device: All
 - Android Version: All

**Additional context**
What I have done so far:
- Hold reference to CognitoCachingCredentialsProvider (as didn't see any way to get hold of it from TransferUtility) and clear/clearCredentials after exception.
- Recreate TransferUtility & S3Client after exception.
- Relaunching app fixes issue.

**Comment by kvasukib** [comment]
@k-thorat Sorry for the inconvenience caused. Are you executing a transfer operation that exceeds 1 hour?

**Comment by ukevgen** [comment]
@kvasukib Hi, have you any updates for this issue? 
I have the same error, but from my customer. This issue happens on the screen were I use TransferUtility, but I think that  transfer operation doesn't  exceeds 1 hour. Can it happens when user is trying to upload photo and lost his connection during an hour?

**Comment by k-thorat** [comment]
@kvasukib Thank you your efforts on maintaining repo. Transfers are not taking longer than hour. 

I think, I miss read how S3Client/CognitoCachingCredentialsProvider works. Now, I am getting session (CognitoUserPool.getSessionInBackground) before using TransferUtility that fixed issue.

Is there any other/better way of handling sessions? Thought about updating CognitoCachingCredentialsProvider after getting session, but that will not cover all the scenarios.

**Comment by kvasukib** [comment]
@k-thorat Sorry for the delayed response. 

1) From your response, I can see that you are authenticating your user with Cognito UserPools, retrieving the token and federating it with `CognitoCachingCredentialsProvider`. How are you achieving this? Can you post a sample code of this which I can validate to see if the federation works as expected?

2) When CognitoCachingCredentialsProvider is used with AmazonS3Client, for every upload/download operation, AmazonS3Client retrieves the credentials through CognitoCachingCredentialsProvider. So by the time when it's retrieving the credentials, it first checks the cached credentials, if they are valid, it will use them. Otherwise, it makes a network call to fetch the new set of temporary credentials and use it to sign the request to upload/download. This will work seamlessly when you use the `Unauthenticated role` in your Cognito identity pool.

However if you are using the Authenticated role (which means you are federating a token with CognitoCachingCredentialsProvider), if the token expired while fetching the new set of credentials, you may not be able to retrieve AWS Credentials. Are you making sure a valid token is federated with CognitoCachingCredentialsProvider before the AmazonS3Client tries to retrieve the credentials from it?
