### ISSUE TITLE
AWS Rekognition

### ISSUE THREAD

**Issue by VirRajpurohit** [aws-amplify/aws-sdk-android#687]
**Rekognition**

Already I have raised the issue in [THIS THREAD](https://github.com/aws-amplify/aws-sdk-android/issues/639)

After going through samples and documentation it is being difficult to integrate Face Rekognition.

[SDK](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-rekognition) and [samples](https://github.com/awslabs/aws-sdk-android-samples) do not include steps and code for AWS Rekognition service integration in Android.

**Comment by minbi** [comment]
Hi @VirRajpurohit ,

What issue are you having with the integration process? In the other thread your main concern was setting up authentication to the service. Has that been resolved? Which features are you looking to implement? I can help you in this thread and potentially pin this thread for those looking for more information.

We have a limited set of samples because samples require a certain level of support that we want to be able to provide.

**Comment by VirRajpurohit** [comment]
@minbi  Actually the setup is bit confusing as per the sample and the documentation and then the code sample provided in another thread.

I want sample to be added in SDK sample as other samples are added with proper explanation.

**Comment by VirRajpurohit** [comment]
@minbi Any update on my query?

**Comment by muellerfr** [comment]
Hi @VirRajpurohit, we're treating this as a feature request, and will discuss with the team. We will update the thread when we have an update.

**Comment by desokroshan** [comment]
@VirRajpurohit We have added some basic integration test that demonstrates labeling an image with a category. We do no have any immediate plans for adding samples app for Rekognition since we want to be able to provide certain degree of support on all of our sample apps which is harder to achieve as samples become more numerous. Please let us know your use case and we will try to add an integration test for it instead.

**Comment by VirRajpurohit** [comment]
@desokroshan Simply I want to achieve the face rekognition feature more specifically face matching.

The issue is the integration process for mobile and samples I have gone through are not helping me as it is becoming quite tough to understand. 

The other samples that have been added in Github as samples are well documented as well as steps are much clear so if you guys can help me out to understand stepwise procedure to integrate Face Rekognition SDK in Android.

**Comment by brianbaliat** [comment]
I agree... you've made the process of integration to an existing system a nightmare...I would really recommend having samples for Android (mobile)

**Comment by VirRajpurohit** [comment]
@minbi 
Can we expect any update on the same?

**Comment by richardmcclellan** [comment]
The recommended approach now for using AWS Rekognition is via the [Amplify.Predictions Android API](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/android).  The most common use cases (text translation, text recognition from an image, labeling entities in an image, etc) can be used directly with `Amplify.Predictions`.

For less common use cases (such as face matching), you can [use the predictions escape hatch](https://docs.amplify.aws/lib/predictions/escapehatch/q/platform/android) to obtain a direct reference to the Rekognition client, already configured for authentication.  Just make sure to use [`Amplify.Auth`](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android) to authenticate prior to using the Rekognition client.

```
// Obtain reference to the plugin
AWSPredictionsPlugin predictionsPlugin = (AWSPredictionsPlugin)
        Amplify.Predictions.getPlugin("awsPredictionsPlugin");
AWSPredictionsEscapeHatch escapeHatch = predictionsPlugin.getEscapeHatch();

// Send a new request to the Rekognition endpoint directly using the client
AmazonRekognitionClient client = escapeHatch.getRekognitionClient();
CompareFacesRequest request = new CompareFacesRequest()
                .withSourceImage(source)
                .withTargetImage(target)
                .withSimilarityThreshold(similarityThreshold);
CompareFacesResult compareFacesResult = rekognitionClient.compareFaces(request);
```
