### ISSUE TITLE
Manually expire or invalidate tokens and get new issued.

### ISSUE THREAD

**Issue by grohj** [aws-amplify/aws-sdk-android#696]
**State your question**
We are using IdToken to identify user in our backend. The IdToken contains information like users name, etc. If user decides to change his personal information, this changes doesn't propagate into existing IdToken. Data is present in the token upon its refresh.

Is there a way to invalidate existing tokens, and force the pool to issue new one?
Btw logging out and loggin in again is out of question, because we are using passwordless login procedure.

**Which AWS Services are you utilizing?**
Cognito

**Environment(please complete the following information):**
 - SDK Version: 2.11.0

**Comment by minbi** [comment]
Hi @grohj ,

We don't currently support re-fetching the id token when it is not expired.
There are two approaches that come to mind.
1. Maintain the personal information yourself and pass along this information to any relevant code flows.
2. If you are issuing refresh tokens, you may try to clear the id token and access token from the SharedPreferences and attempt to refresh the tokens (forcing). This obviously breaks the abstraction that the SDKs provide.

I will check with the service team to see if there are any other flows available for you to use.

**Comment by minbi** [comment]
Hi @grohj ,

You will need to force refresh the tokens using the method in my previous post. We will investigate adding exposing this functionality in our clients.

**Comment by grohj** [comment]
Hi @minbi ,

I really appreciate your response. I used basically the first option you provided. The second one is hacky approach which I won't take my chances with.

Anyways, glad you are considering to add this feature, looking forward to see it :)

Thanks.

**Comment by Mehdi-android** [comment]
> Hi @grohj ,
> 
> We don't currently support re-fetching the id token when it is not expired.
> There are two approaches that come to mind.
> 
> 1. Maintain the personal information yourself and pass along this information to any relevant code flows.
> 2. If you are issuing refresh tokens, you may try to clear the id token and access token from the SharedPreferences and attempt to refresh the tokens (forcing). This obviously breaks the abstraction that the SDKs provide.
> 
> I will check with the service team to see if there are any other flows available for you to use.

Hello, 
Can you please tell me in detail how to go forward with second approach.


Thanks

**Comment by atthapon-k** [comment]
@Mehdi-android 
Did you solve this?

**Comment by sachinavm12** [comment]
Hi @minbi,

Any update on this as it is a valid use case when using custom claims?

**Comment by desokroshan** [comment]
@sachinavm12 At this point we do not have an update on this feature. I have added this to the https://github.com/aws-amplify/aws-sdk-android/issues/634 for tracking. We will post an update once the feature is released.

**Comment by CodeBreak524** [comment]
Hi, @desokroshan 

Can you provide any new info about when this feature is going to be done? 

Btw it seems that this feature is already done in iOS SDK and presented as `clearSession()` method for User identity. It clears cached session from memory and idToken and accessToken from preferences. It looks like smth like that should be good enough solution for this feature either.

**Comment by mangeshsambare** [comment]
Hi,
How can I get ID token forcefully even it is not expired. 
Any updates on this issue??

**Comment by joeboyscout04** [comment]
Is this anything you'd consider accepting a pull request for?  It's been blocking our development for quite a while, especially painful considering it's already present on iOS.

**Comment by hamen** [comment]
As reference, I'm tracking our closed ticket https://github.com/aws-amplify/aws-sdk-android/issues/2637 here as well.

It's unfortunate that this is not prioritized and we can't have feature parity with the iOS SDK.

**Comment by LizDodion** [comment]
agree that this is unfortunate as it would be great to have a solution to this.

**Comment by jonreeve** [comment]
Note there's a (very fragile) workaround over on [this related ticket](https://github.com/aws-amplify/amplify-android/issues/919#issuecomment-917879951), to do this by accessing a private field and 3 private functions. Would be so good, so appreciated, if that was exposed properly, stable, supported, etc. However for us poor saps trying to make this work in the meantime, that may be the only option for now 🤷

**Comment by frimfram** [comment]
Hello all ,  here is a test that uses ```revokeTokens``` method  of CognitoUser.  are your use cases something similar?

https://github.com/aws-amplify/aws-sdk-android/blob/0681a5ca00e47d73885ba55460e27776e5493612/aws-android-sdk-mobile-client/src/androidTest/java/com/amazonaws/mobile/client/AWSMobileClientTest.java#L484

As a reference, this is the revokeTokens implementation.  Please let us know if this function would work for you or you would like a function with different behaviors.  Thanks!

https://github.com/aws-amplify/aws-sdk-android/blob/0681a5ca00e47d73885ba55460e27776e5493612/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L2340

**Comment by PS-MS** [comment]
Hi @frimfram,

This doesn't work for my use case, for me it is an attempt to support dynamic auth groups within DataStore.

My issue is that when a user is added to a new Cognito group their current token isn't updated with the new group, this is understandable, so to retrieve the new group I would like the login token to be revoked and a new one issued without the user needing to sign in again.

**Comment by frimfram** [comment]
Revoking tokens and issuing new one automatically in one function can lead to big security hole so we'll need to evaluate implication thoroughly.  Here are some discussions on a related problem:  https://github.com/aws-amplify/amplify-js/issues/1213#issuecomment-414181560

In the meantime, something like using "revokeTokens" to clean up the user session and calling "signIn" function may work.

**Comment by PS-MS** [comment]
The main issue for my use case is simply that a users current token doesn't reflect their real time cognito groups and signing out and back in or revoking and issuing a token is just a work around for that issue to give the user their real permissions.

It sounds like for me, and the others in this thread, we just need a way to update the information stored with the current token so that it matches any changes made to the back end

**Comment by jonreeve** [comment]
@frimfram Thanks but the request here is specifically to avoid signing the user out and the poor UX that leads to. As for security concerns, the thing being asked for is parity with a feature the [iOS SDK already offers](https://github.com/aws-amplify/aws-sdk-android/issues/2637#issue-998005999), so worth checking that out regarding those. Obviously caution is justified but perhaps their implementation could inform this one.

**Comment by frimfram** [comment]
@jonreeve  sorry that it was not clear.
The parity with a feature in the iOS SDK already exists in Android SDK:  The naming of the function is different - instead of User.clearSession (in iOS), there is User.revokeTokens (in Android).  Please try revokeTokens and see if that works for you.  The details of revokeTokens are in my previous post here:  
https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-960430659


iOS does not support clearing and auto generation of session in one function (proactive refresh):
https://github.com/aws-amplify/amplify-ios/issues/1179
Proactive refresh would easily lead to security hole so recommend clearing session and log in users again.

**Comment by jonreeve** [comment]
@frimfram in the issue you linked to, there's [this comment](https://github.com/aws-amplify/amplify-ios/issues/1179#issuecomment-843946249) that describes using `clearSession` and then calling `fetchAuthSession`. As they note there, the [documentation of `clearSession` says](https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.h#L242-L246): "Remove the id and access token from the keychain, but keep the refresh token. Use this when you have updated user attributes and want to refresh the id and access tokens.". That's exactly what we're after here: clear the id and access token, not the refresh token. In the iOS version of the app we're working on, they simply call this function, and the next thing that uses it triggers it to refresh those tokens, and does not sign the user out, but does update the user attributes.

This is the implementation of this function on iOS for reference: https://github.com/aws-amplify/aws-sdk-ios/blob/main/AWSCognitoIdentityProvider/AWSCognitoIdentityUser.m#L1465-L1473

The `clearCachedTokens` function you linked, as you said, is called from `signOut`. It is actually very similar to the iOS `clearSession` function, but it also clears the refresh token. We're not interested in signing the user out just to refresh some attributes that have changed on the back-end about them.

`revokeTokens` appears to be something a bit more than that, actually issuing a request to the back-end to revoke them I guess? It doesn't look similar to the iOS function we're asking about in purpose or in implementation. Regardless, I tried calling it as you've advised, where we want this to happen, and I'm afraid it didn't seem to have any effect. I don't seem to get signed out, but also the user attributes are still outdated, and the ID and access tokens seem to have the same values before and after calling it.

What **does** currently work for us, for comparison, is [this approach that currently requires reflection to access](https://github.com/aws-amplify/amplify-android/issues/919#issuecomment-917879951). What we're looking for is a function on the Android SDK to clear id + access token but NOT refresh token, so that the tokens (and thus the user attributes that have changed) will be refreshed upon next use, exactly as currently happens on the iOS SDK.

**Comment by jmcanache** [comment]
Hello Everyone. Is there any update on this subject? For the momento I'm applying the solution @minbi propose, with the clear manually of the idToken and accessToken from sharedPreferences and then forcing a refresh. But I don't know how dangerous is this.

**Comment by div5yesh** [comment]
Please use the following as a workaround until we find a proper solution:

Set the refresh threshold higher than current expiration of idToken or accessToken to force a refresh. During the subsequent getTokens calls, the library will fetch new tokens as long as refreshToken is not expired.

`CognitoIdentityProviderClientConfig.setRefreshThreshold(thresholdInMS);` where **thresholdInMS** is the refresh threshold in milliseconds and if it is greater than the token expiration forces a token refresh request.

```java
new Thread(() -> {
    try {
    CognitoIdentityProviderClientConfig.setRefreshThreshold(100000);
    AWSMobileClient.getInstance().getTokens();
    } catch (Exception e) {
        e.printStackTrace();
    }
}).start();
```

**Comment by tjleing** [comment]
If the workaround does not work, please comment on this issue or open a new one.

**Comment by orcuns** [comment]
> Please use the following as a workaround until we find a proper solution:
> 
> Set the refresh threshold higher than current expiration of idToken or accessToken to force a refresh. During the subsequent getTokens calls, the library will fetch new tokens as long as refreshToken is not expired.
> 
> `CognitoIdentityProviderClientConfig.setRefreshThreshold(thresholdInMS);` where **thresholdInMS** is the refresh threshold in milliseconds and if it is greater than the token expiration forces a token refresh request.
> 
> ```java
> new Thread(() -> {
>     try {
>     CognitoIdentityProviderClientConfig.setRefreshThreshold(100000);
>     AWSMobileClient.getInstance().getTokens();
>     } catch (Exception e) {
>         e.printStackTrace();
>     }
> }).start();
> ```

This workaround doesn't work. This threshold is not big enough to trigger for new AccessToken. Also, I can't set more than 1800000. 
`private static final long REFRESH_THRESHOLD_MAX = 1800 * 1000;` CognitoIdentityProviderClientConfig.class.

Is there anything I'm missing @div5yesh ?
