### ISSUE TITLE
Unable to get android kinesis to stream to the console

### ISSUE THREAD

**Issue by thebehera** [aws-amplify/aws-sdk-android#707]
**Unable to get a stream to work.**
When I run the [AmazonKinesisVideoDemoApp](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonKinesisVideoDemoApp) I am unable to get the stream to show up on the Amazon Kinesis Video Streams Console page.

**To Reproduce**
A code sample or steps:

- clone https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonKinesisVideoDemoApp
- modify lines 6,7, 16,17,18 & 19 on `AmazonKinesisVideoDemoApp/src/main/res/raw/awsconfiguration.json`
- modify line 16 on `AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/KinesisVideoDemoApp.java`
- replace line 169 on `AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/fragment/StreamConfigurationFragment.java` from 
`                      .withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS)
` to 
`                        .withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_NALS)` -- this was required to prevent the error `Failed to put a frame into the stream`
- Updated the KEY_STREAM_NAME in the `AmazonKinesisVideoDemoApp/src/main/java/com/amazonaws/kinesisvideo/demoapp/fragment/StreamingFragment.java` to match the stream `demo-stream` that I am using

**Which AWS service(s) are affected?**
aws-sdk-android-samples/AmazonKinesisDemoApp

**Expected behavior**
- Log in, set the `Stream Name` to `demo-stream`, then select `Stream`
- I expect the stream to show up here: https://console.aws.amazon.com/kinesisvideo/streams/streamName/demo-stream?region=us-east-1

**Screenshots**
The error image when looking at the console
![image](https://user-images.githubusercontent.com/2779689/52884989-51fbe080-3135-11e9-8df2-2f2a028eeaea.png)

Now I notice there is an issue with the timestamp, but I didn't modify any code so I'm not sure if that is what might be causing the issue.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 
https://github.com/awslabs/aws-sdk-android-samples/commit/2d700d6f8180e7ea59df199f069ee74942422860
 - Device: Pixel 3 XL
 - Android Version: 9
 - Specific to simulators: No

What do I need to do to get a stream to work from Android?

**Comment by kvasukib** [comment]
@thebehera Sorry for the inconvenience caused. We are looking into the issue.

**Comment by MushMal** [comment]
@thebehera , we are aware of the producer timestamp "drift" caused by the inconsistency in the default time implementation which would use nanotime vs the system millis on Linux/Android based platforms. We will issue a fix soon. However, this should not affect the playback in the console. From the screen shot it seems that the console was able to retrieve the "Codec Private Data" which shows a resolution of 320x240 with baseline profile. However, your browsers decoder throws an exception decoding it.

Could you please provide a little more information about the scenario.

* Are you using h264 or some other encoding - NOTE: the console playback currently supports ONLY h264 stream playback.
* In order to eliminate the potential producer-side issue, would you please email the logcat log from the run (you can capture the log from the beginning for a minute or so) and email it to kinesis-video-support@amazon.com
* Could you change the resolution in the demo app from sub-SD to SD (like 640x480) or HD resolution and include the results?

**Comment by thebehera** [comment]
@MushMal  Hi thanks for the update.
To answer your questions: 

- I am only using H264. Here's the screen shot of what the android app shows:
![image](https://user-images.githubusercontent.com/2779689/52976863-c5e5f500-3390-11e9-886d-dfdfdd242dda.png)
- Done. Email has been sent!

**Comment by palpatim** [comment]
@thebehera Checking to see if this issue was resolved via your conversation with support?
