### ISSUE TITLE
[S3] AmazonS3Client putObject throws NPE due to ETag being null in the returned object metadata

### ISSUE THREAD

**Issue by since2014** [aws-amplify/aws-sdk-android#717]
**Describe the bug**
```
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
 at com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:64)
```
**x-amz-request-id**
 27DBF521DFDAFAF9

**x-amz-id-2**: QT2WH/C8fp1G2ClBNIYZBBaqEr7y79qStDGAmsS7dWYkm8000w9uuLTlNePXXt8JHtonNKmLnn4=

*AmazonS3Client.putObject*
```
            final byte[] serverSideHash = BinaryUtils.fromHex(returnedMetadata.getETag());
```

**Which AWS service(s) are affected?**
s3 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.11.0

**Comment by sunchunqiang** [comment]
Hi, @since2014 , Can the issue be reproduced? If yes, how to reproduce the issue.

**Comment by kvasukib** [comment]
@since2014 Sorry for the inconvenience caused. This issue occurred due to the ETag in the `ObjectMetadata` returned from S3 being null. Hence, the SDK couldn't compute the server side hash from the ETag.

When you try to upload an object using `putObject`, after the data has been uploaded and the response is received from S3, the SDK computes the MD5 hash of the data on the client side and verifies it it matches with the server side hash (hash computed from the ETag returned in the ObjectMetadata).

There could be two possibilities here:
1) S3 did not send the ETag in the response
2) S3 sent the ETag but the SDK couldn't unmarshall the response correctly, thus ETag returned to be null.

To verify the above, can you provide us the following details:

1) Size of the file being uploaded
2) Is this issue consistently reproducible for every upload? Can you reproduce this on your development environment? If so, we need the following information:
    2.1) Values in `returnedMetadata` object
3) Is the file uploaded on your S3 bucket correctly?
4) Is versioning enabled for the object or bucket?
5) Is Server-Side Encryption enabled for this object or bucket?

**Comment by since2014** [comment]
Details: 
1. Size of the file being uploaded.  *Most file sizes are with in 1Mb.*
2. Is this issue consistently reproducible for every upload? Can you reproduce this on your development environment? If so, we need the following information: *Yes, it is consistently reproducible for every upload*
    2.1) Values in `returnedMetadata` object *I will provide this information later.*
3. Is the file uploaded on your S3 bucket correctly? *File uploaded correctly*
4. Is versioning enabled for the object or bucket? *No*
5. Is Server-Side Encryption enabled for this object or bucket? *No*

**Comment by kvasukib** [comment]
@since2014 Sorry for the delayed response. I couldn't reproduce the issue for files of sizes within 1MB.  Are you able to reproduce this problem now? If so, can you paste a code snippet?

What is the content type of the file you are uploading?
