### ISSUE TITLE
Stream video rotated by 90 degrees on Kinesis Stream

### ISSUE THREAD

**Issue by mrkiwi** [aws-amplify/aws-sdk-android#854]
**Describe the bug**
The streaming video in Kinesis Video Stream Console shows with wrong orientation. Both modes (landscape and portrait) have the same stream rotation on console preview  - 90 degrees. Also withCameraOrientation() for AndroidCameraMediaSourceConfiguration does not fix this, stream not event react to this value.

**To Reproduce**
Configure Camera Media Source with with this parameters:
```
AndroidCameraMediaSourceConfiguration.builder()
.withCameraId("0")
.withEncodingMimeType("video/avc")
.withHorizontalResolution(320)
.withVerticalResolution(240)
.withCameraFacing(0)
.withIsEncoderHardwareAccelerated(true)
.withFrameRate(20)
.withRetentionPeriodInHours(1)
.withEncodingBitRate(128 * 1024)
.withCameraOrientation(-90)
.withIsAbsoluteTimecode(false));
```

**Which AWS service(s) are affected?**
Kinesis Video Streams

**Expected behavior**
Expected result is getting correct rotation for stream for portrait mode and make withCameraOrientation() method works.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.6
 - Device: Google Pixel 2 XL
 - Android Version: 9

**Additional context**
I reproduce this issue on different devices.

**Comment by palpatim** [comment]
@MushMal Can you take a look at this one?

**Comment by MushMal** [comment]
Apologies for the delay. There are two scenarios to consider:

1) Setting the orientation at the start of the streaming on the device.
2) Setting the orientation dynamically as the customer rotates the device while streaming.

#2 we don’t support in the demo application because it would require a few changes in the application. The main issue here is that as the orientation changes require updated CPD (Codec Private Data - for H264 it's the SPS/PPS). This requires seamless re-streaming when the application detects the rotation. The preview screen doesn't require any changes but the KVS streaming needs an updated CPD as the playback on the other end will not work.
 
As for #1 – there seem to be a minor bug somewhere in the application settings. We will look into it in the priority order.

**Comment by dayona** [comment]
> Apologies for the delay. There are two scenarios to consider:
> 
>     1. Setting the orientation at the start of the streaming on the device.
> 
>     2. Setting the orientation dynamically as the customer rotates the device while streaming.
> 
> 
> #2 we don’t support in the demo application because it would require a few changes in the application. The main issue here is that as the orientation changes require updated CPD (Codec Private Data - for H264 it's the SPS/PPS). This requires seamless re-streaming when the application detects the rotation. The preview screen doesn't require any changes but the KVS streaming needs an updated CPD as the playback on the other end will not work.
> 
> As for #1 – there seem to be a minor bug somewhere in the application settings. We will look into it in the priority order.

I am Still facing this issue - scenario 1)
Is there a change which fixed it ?

Device Oneplus 6 
Camera preview on device Is correct but on web application its rotated Left .

**Comment by artakka-isp** [comment]
Wrong orientation

**Comment by namaha-app** [comment]
@MushMal  We are still facing the issue. This has been reproduced in multiple devices
