### ISSUE TITLE
AWSMobileClient.getCredentials() locks the thread

### ISSUE THREAD

**Issue by nchorniy** [aws-amplify/aws-sdk-android#924]
**Description / Question**
In our app, when the SDK detects that tokens are expired (which may or may not reflect real token expiration on Cognito side, see #679), we follow the [documentation advice](https://aws-amplify.github.io/docs/android/authentication#cognito-user-pool-tokens) and try to relogin the user. However, the actual relogin may happen hours and even days later (device may not have network connection or network is available but there is no internet connection available). But our application should still collect data (in background) and store/send it to the backend (using AppSync).

The problem comes with every call to `AWSMobileClient.getCredentials()` method (called by any AWS service that we use: AppSync, S3, Lambda, DynamoDB). Since the user token's state is `SIGNED_OUT_USER_POOLS_TOKENS_INVALID`, `AWSMobileClient.waitForSignIn()` method locks the thread in which the `AWSMobileClient.getCredentials()` is called. The lock happens in the line `mWaitForSignInLock.lock()`.

Questions:
1. What are the possible consequences if user doesn’t get signed in for a long time, but the code will still try to communicate AWS services in an authenticated way? Can it potentially just produce and lock all available threads?
1. What is the best practice here?
1. Can `AWSMobileClient.getCredentials()` be reworked so that it doesn’t block the thread in the described case?

**Utilized AWS Services**
AppSync, DynamoDB, S3, Lambda

**Code snippets**

May happen while app is in background:
```kotlin
override fun onUserStateChanged(details: UserStateDetails) {
   val state = details.userState
   if (state === UserState.SIGNED_OUT_USER_POOLS_TOKENS_INVALID || state === UserState.SIGNED_OUT_FEDERATED_TOKENS_INVALID) {
       //schedule sign-in which may happen hours or days later
   }
}
```

`AWSMobileClient`
```java
//this code is being called from `getCredentials` which in turn might be called by AppSync, Lambda, DynamoDB, S3
protected boolean waitForSignIn() {
   try {
       //code gets locked here 
       mWaitForSignInLock.lock();
       mSignedOutWaitLatch = new CountDownLatch(1);
    …
   }
```

**Environment:**
 - SDK Version: 2.13.2

**Device Information:**
 - Device: Any Android device that we tested on (Pixel 1, Samsung Galaxy J7 2016 and others)
 - Android Version: 8.0.0, 8.1.0

**Comment by markorakita** [comment]
Related: #951

**Comment by markorakita** [comment]
@nchorniy From my understanding, every time the AWSMobileClient is initialized, it uses cashed refresh tokens to refresh user identity, and in the same time it puts new refresh tokens in the cache. Only scenario when user can get into SIGNED_OUT_USER_POOLS_TOKENS_INVALID state is when the app couldn't initialize client for a long time (depending on what you set as refresh token expiration time). In that case, when your UserStateListener() detects that user state is SIGNED_OUT_USER_POOLS_TOKENS_INVALID, you can just redirect him to your login page, or you can have some flag in your code so that whenever user tries something that requires aws access you tell him that he needs to login again (lot of apps do this). It is rare occasion and shouldn't bother user much, especially if you set refresh token expiration time to some large value like 10 years.

One edge case is when user was offline, then he suddenly got internet connection, app tried to call some AWS service, SIGNED_OUT_USER_POOLS_TOKENS_INVALID happened and call blocked. Prevention of this is that you **never** try to call any AWS service without first checking if AWSMobileClient was initialized. When it is initialized it returns UserStateDetails so you can know that tokens are invalid and avoid calls to AWS services, so block is avoided.


@desokroshan Please correct me if I my understanding was incorrect. For example I am not 100% sure if new refresh tokens are cashed every time that AWSMobileClient is initialized.

**Comment by minbi** [comment]
Hi @nchorniy ,  Does @markorakita 's answer help?

A small tidbit to add is: Inside your state listener, when the SIGNED_OUT_USER_POOLS_TOKENS_INVALID state is triggered, you can determine from your own parameters (online/offline, current activity) whether you want to sign-in again or `releaseSignInWait()` to allow the blocked calls to fail. Then the app can just handle the failure case and move on.
